<div class="profile container content">
    	<div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <?php if($this->identity()->getImage() != null): ?>
                <img class="img-responsive profile-img margin-bottom-20" src="<?php echo '/uploads/users' . DIRECTORY_SEPARATOR . $this->identity()->getId() . DIRECTORY_SEPARATOR . 'square264x264_' . $this->identity()->getImage(); ?>" alt="<?php echo $user->getFirstName() . " " . $user->getLastName(); ?>">
                <?php else: ?>
                <img class="img-responsive md-margin-bottom-10" src="/frontend/img/noavatar.png" alt="<?php echo $this->identity()->getFirstName() . " " . $this->identity()->getLastName(); ?>">
                <?php endif; ?>
                <?php echo $this->navigation('admin_navigation')->menu()->setUlClass('list-group sidebar-nav-v1 margin-bottom-40')->setAddClassToListItem(true)->escapeLabels(false); ?>
                <hr>
            </div>
            <!--End Left Sidebar-->
            
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <!--Table Search v2-->
                    <a href="<?php echo $this->url('administrator/default', array('controller' => 'user', 'action' => 'create-first-step' )); ?>" class="btn-u btn-brd btn-brd-hover btn-u-dark btn-u-xs pull-left margin-bottom-20">Add User</a>
                    <div class="table-search-v2 margin-bottom-20">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>User Image</th>
                                        <th class="hidden-sm">Name</th>
                                        <th>Status</th>
                                        <th>Contacts</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($users as $user): ?>
                                    <tr>
                                        <td>
                                        <?php if($user->getImage() === null): ?>
                                            <img class="img-responsive md-margin-bottom-10" src="/frontend/img/noavatar_60x60.png" alt="<?php echo $user->getFirstName() . " " . $user->getLastName(); ?>">
                                        <?php else: ?>
                                            <img class="rounded" src="<?php echo $filesDir . DIRECTORY_SEPARATOR . $user->getId() . DIRECTORY_SEPARATOR . 'square60x60_' . $user->getImage(); ?>" alt="<?php echo $user->getFirstName() . " " . $user->getLastName(); ?>">
                                        <?php endif; ?>
                                        </td>
                                        <td class="td-width">
                                            <h3><a href="<?php echo $this->url('administrator/default', array('controller' => 'user', 'action' => 'view', 'id' => $user->getId() )); ?>"><?php echo $user->getFirstName() . " " . $user->getLastName(); ?></a></h3>
                                            <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id commodo lacus. Fusce non malesuada ante. Donec vel arcu.</p>
                                            <small class="hex">Joined February 28, 2014</small> -->
                                        </td>
                                        <td>
                                            <?php if ($user->getRole() != null): ?>
                                                <?php if ($user->getRole()->getName() == 'administrator'): ?>
                                                    <span class="label label-success">Administrator</span>
                                                <?php elseif ($user->getRole()->getName() == 'franchisor'): ?>
                                                    <span class="label label-info">Franchisor</span>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </td>
                                        <td>
                                            <ul class="list-inline s-icons">
                                                <?php if ($user->getFacebook()): ?>
                                                <li>
                                                    <a data-placement="top" data-toggle="tooltip" class="tooltips" data-original-title="Facebook" href="<?php echo $user->getFacebook(); ?>">
                                                        <i class="fa fa-facebook"></i>
                                                    </a>
                                                </li>
                                                <?php endif; ?>
                                                <?php if ($user->getTwitter()): ?>
                                                <li>
                                                    <a data-placement="top" data-toggle="tooltip" class="tooltips" data-original-title="Twitter" href="<?php echo $user->getTwitter(); ?>">
                                                        <i class="fa fa-twitter"></i>
                                                    </a>
                                                </li>
                                                <?php endif; ?>
                                                <?php if ($user->getLinkedin()): ?>
                                                <li>
                                                    <a data-placement="top" data-toggle="tooltip" class="tooltips" data-original-title="Linkedin" href="<?php echo $user->getLinkedin(); ?>">
                                                        <i class="fa fa-linkedin"></i>
                                                    </a>
                                                </li>
                                                <?php endif; ?>
                                            </ul>
                                            <span><a href="#"><?php echo $user->getEmail(); ?></a></span>
                                            <!-- <span><a href="#">www.htmlstream.com</a></span> -->
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>    
                    </div>
                    <!--End Table Search v2-->
                </div>
                <!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div>