<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('FRYDAY '. $this->translate('One Of The Largest Networks Of Cosmopolitan Professionals'))->setSeparator(' - ')->setAutoEscape(false) 
        ; ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ; ?>

        <!-- STYLES -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/backend/css/style.css')
            ->prependStylesheet($this->basePath() . '/backend/plugins/font-awesome-4.2.0/css/font-awesome.css')
            ->prependStylesheet($this->basePath() . '/backend/plugins/bootstrap-3.2.0/dist/css/bootstrap.css')
            ->prependStylesheet($this->basePath() . '/backend/plugins/bootstrap-3.2.0/dist/css/bootstrap-theme.css')
        ; ?>

        <!-- SCRIPTS -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/backend/plugins/bootstrap-3.2.0/dist/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/backend/plugins/jquery-ui-1.11.1/jquery-ui.js')
            ->prependFile($this->basePath() . '/backend/plugins/jquery/jquery-2.1.1.js')
        ; ?>

    </head>
    <body>
        <!-- NAVBAR  -->
        <header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php //cho $this->url('backend/default', array('controller' => 'index', 'action' => 'index')); ?>">FRYDAY ADMINISTRATOR</a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav')->setMaxDepth(0); ?>
<!--                         <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php //echo $this->url('backend/default', array('controller' => 'index', 'action' => 'index')); ?>">Home</a></li>
                            <li><a href="#about">Content</a></li>
                        </ul> -->
                </div>
            </div>
        </header>

        <div class="container-fluid">
            <!-- SUB MENU -->
            <br>
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1">
                    <?php 
                        // The first variant of rendering
                        // echo $this->navigation('navigation')->menu()->setMaxDepth(1)->setMinDepth(1)->setOnlyActiveBranch(true)->setUlClass('nav nav-tabs');
                        // The second variant via options
                        echo $this->navigation('navigation')->menu()->renderMenu(null, array('ulClass' => 'nav nav-tabs', 'minDepth' => 1, 'maxDepth' => 1, 'onlyActiveBranch'  => true));
                    ?>
                </div>
            </div>
            <br>

            <!-- MAINCONTENT  -->
            <?php echo $this->content; ?>
        </div>

        <script type="text/javascript"> 
            $('.collapse').on('shown.bs.collapse', function (e) {
                $('.collapse').not(this).removeClass('in');
            });

            $('[data-toggle=collapse]').click(function (e) {
                $('[data-toggle=collapse]').parent('li').removeClass('active');
                $(this).parent('li').toggleClass('active');
            });
        </script>

    </body>
</html>
