<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('FRYDAY '. $this->translate('One Of The Largest Networks Of Cosmopolitan Professionals'))->setSeparator(' - ')->setAutoEscape(false) 
        ; ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ; ?>

        <!-- STYLES -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/backend/css/style.css')
            // ->prependStylesheet($this->basePath() . '/backend/plugins/bootstrap-fileinput/css/fileinput.css')
            ->prependStylesheet($this->basePath() . '/backend/plugins/font-awesome-4.2.0/css/font-awesome.css')
            ->prependStylesheet($this->basePath() . '/backend/plugins/bootstrap-3.2.0/dist/css/bootstrap.css')
            ->prependStylesheet($this->basePath() . '/backend/plugins/bootstrap-3.2.0/dist/css/bootstrap-theme.css')
        ; ?>

        <!-- SCRIPTS -->
        <?php echo $this->headScript()
            // ->prependFile($this->basePath() . '/backend/plugins/bootstrap-fileinput/js/fileinput.js')
            // ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js')
            ->prependFile($this->basePath() . '/backend/plugins/bootstrap-3.2.0/dist/js/bootstrap.min.js')
        ; ?>

    </head>
    <body>
        <!-- NAVBAR  -->
        <header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('backend/default', array('controller' => 'index', 'action' => 'index')); ?>">Fryday Administrator</a>
                </div>
                <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php echo $this->url('backend/default', array('controller' => 'index', 'action' => 'index')); ?>">Home</a></li>
                            <li><a href="#about">Content</a></li>
                        </ul>
                </div><!--/.nav-collapse -->
            </div>
        </header>

        <div class="container-fluid">
        <!-- <div class="container"> -->
            <!-- BREADCRUMB -->
            <ol class="breadcrumb">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">2013</a></li>
                <li class="active">November</li>
            </ol>

            <!-- MAINCONTENT  -->
            <?php echo $this->content; ?>
        </div>
    </body>
</html>
