<div class="row">
	<div class="col-lg-12">
		<div class="page-header col-lg-7 col-lg-offset-2">
		  	<h2>Creating a New User <!-- <small>Subtext for header</small> --></h2>
		</div>
		<?php $form->setAttribute('action', $this->url('backend/default', array('controller' => 'team', 'action' => 'create')))->prepare(); ?>
		<?php echo $this->form()->openTag($form); ?>
		<div class="col-lg-7 col-lg-offset-2">
			
			<div class="row">
	            <?php echo $this->formLabel($this->form->get('firstName')); ?>
	            <div class="input-group input-group-sm col-lg-6">
	                <?php echo $this->formInput($this->form->get('firstName')); ?>
	                <?php echo $this->FormElementErrors($this->form->get('firstName')); ?>
	            </div>
            </div>

			<div class="row">
	            <?php echo $this->formLabel($this->form->get('lastName')); ?>
	            <div class="input-group input-group-sm col-lg-6">
	                <?php echo $this->formInput($this->form->get('lastName')); ?>
	                <?php echo $this->FormElementErrors($this->form->get('lastName')); ?>
	            </div>
            </div>

			<div class="row">
	            <?php echo $this->formLabel($this->form->get('profileImage')); ?>
	            <div class="input-group input-group-sm col-lg-6">
		            <?php echo $this->formFile($this->form->get('profileImage')); ?>
		            <?php echo $this->FormElementErrors($this->form->get('profileImage')); ?>
	            </div>
	        </div>

			<div class="row">
	            <?php echo $this->formLabel($this->form->get('login')); ?>
	            <div class="input-group input-group-sm col-lg-6">
	                <?php echo $this->formInput($this->form->get('login')); ?>
	                <?php echo $this->FormElementErrors($this->form->get('login')); ?>
	            </div>
            </div>

			<div class="row">
	            <?php echo $this->formLabel($this->form->get('password')); ?>
	            <div class="input-group input-group-sm col-lg-6">
	                <?php echo $this->formInput($this->form->get('password')); ?>
	                <?php echo $this->FormElementErrors($this->form->get('password')); ?>
	            </div>
            </div>

            <div class="row">
	            <?php echo $this->formLabel($this->form->get('role')); ?>
	            <div class="input-group input-group-sm col-lg-6">
	                <?php echo $this->formSelect($this->form->get('role')); ?>
	                <?php echo $this->FormElementErrors($this->form->get('role')); ?>
	            </div> 
        	</div>

            <div class="row">
	            <?php echo $this->formLabel($this->form->get('city')); ?>
	            <div class="input-group input-group-sm col-lg-6">
	                <?php echo $this->formSelect($this->form->get('city')); ?>
	                <?php echo $this->FormElementErrors($this->form->get('city')); ?>
	            </div> 
        	</div>

        	<!-- <div class="row">
	            <?php //echo $this->formLabel($this->form->get('text')); ?>
	            <div class="input-group input-group-sm col-lg-6">
	                <?php //echo $this->formTextarea($this->form->get('text')); ?>
	                <?php //echo $this->FormElementErrors($this->form->get('text')); ?>
	            </div>
	        </div> -->

	        <div class="row">
	            <div class="input-group input-group-sm col-lg-6 col-lg-offset-4">
		            <?php echo $this->formSubmit($this->form->get('submit')); ?>
	            </div>
	        </div>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
	</div>
</div>