<div class="row">
	<div class="col-lg-10 col-lg-offset-1">
		<h4><a href="<?php echo $this->url('backend/default', array('controller' => 'team', 'action' => 'create')); ?>"><i class="fa fa-plus fa-fw"></i> NEW</a></h4>
		<br>
	</div>
</div>

<div class="row">
	<div class="col-lg-10 col-lg-offset-1">
        <!-- FLASH MESSAGE -->
        <?php if(count($flashMessages)) : ?>
            <?php foreach ($flashMessages as $msg) : ?>
                <div class="alert alert-success col-lg-12" role="alert"><?php echo $msg; ?></div>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php //if($errorSaleMessage) : ?>
            <!-- <div class="alert alert-danger col-lg-12" role="alert"><?php echo $errorSaleMessage; ?></div> -->
        <?php //endif; ?>
        <!-- END FLASH MESSAGE -->
    </div>
</div>

<?php foreach ($users as $user): ?>
	<div class="row">
		<div class="col-lg-2 col-lg-offset-1">
			<?php 
			$imageBase64 = null; 
			$imageName = $user->getProfileImage();
			if (file_exists($imageName)) {
				$handle = fopen($imageName, "r");
				$imageBase64 = fread($handle, filesize($imageName));
				fclose($handle);
			}
			?>
			<img src="data:image/png;base64,<?php echo base64_encode($imageBase64) ?>" class="img-rounded" height="96" width="96">
		</div>
		<div class="col-lg-6">
			<h4 class="text-left"><?php echo $user->getFirstName(); ?> <?php echo $user->getLastName(); ?></h4>
			<p class="venue-preview-category"><?php echo $user->getRole()->getName(); ?></p><br>
			<?php if($user->getRole()->getRoleId() == 1): ?>
				<i class="fa fa-map-marker fa-fw"></i><?php echo $user->getCity()->getName(); ?>
			<?php endif ?>
		</div>
	</div>
	<hr class="col-lg-9 col-lg-offset-1">
<?php endforeach; ?>