<?php

namespace DoctrineORMModule\Proxy\__CG__\Admin\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Venue extends \Admin\Entity\Venue implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'name', 'phone', 'website', 'email', 'image', 'xStartCrop', 'yStartCrop', 'widthCrop', 'heightCrop', 'widthCurrent', 'heightCurrent', 'address', 'city');
        }

        return array('__isInitialized__', 'id', 'name', 'phone', 'website', 'email', 'image', 'xStartCrop', 'yStartCrop', 'widthCrop', 'heightCrop', 'widthCurrent', 'heightCurrent', 'address', 'city');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Venue $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', array());

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite($website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', array($website));

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setXStartCrop($xStartCrop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXStartCrop', array($xStartCrop));

        return parent::setXStartCrop($xStartCrop);
    }

    /**
     * {@inheritDoc}
     */
    public function getXStartCrop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXStartCrop', array());

        return parent::getXStartCrop();
    }

    /**
     * {@inheritDoc}
     */
    public function setYStartCrop($yStartCrop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYStartCrop', array($yStartCrop));

        return parent::setYStartCrop($yStartCrop);
    }

    /**
     * {@inheritDoc}
     */
    public function getYStartCrop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYStartCrop', array());

        return parent::getYStartCrop();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeightCrop($heightCrop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeightCrop', array($heightCrop));

        return parent::setHeightCrop($heightCrop);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeightCrop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeightCrop', array());

        return parent::getHeightCrop();
    }

    /**
     * {@inheritDoc}
     */
    public function setWidthCrop($widthCrop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidthCrop', array($widthCrop));

        return parent::setWidthCrop($widthCrop);
    }

    /**
     * {@inheritDoc}
     */
    public function getWidthCrop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidthCrop', array());

        return parent::getWidthCrop();
    }

    /**
     * {@inheritDoc}
     */
    public function setWidthCurrent($widthCurrent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidthCurrent', array($widthCurrent));

        return parent::setWidthCurrent($widthCurrent);
    }

    /**
     * {@inheritDoc}
     */
    public function getWidthCurrent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidthCurrent', array());

        return parent::getWidthCurrent();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeightCurrent($heightCurrent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeightCurrent', array($heightCurrent));

        return parent::setHeightCurrent($heightCurrent);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeightCurrent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeightCurrent', array());

        return parent::getHeightCurrent();
    }

}
