<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            // ->prependStylesheet($this->basePath() . '/font-awesome-4.1.0/css/font-awesome.min.css')
            // ->prependStylesheet($this->basePath() . '/css/plugins/morris.css')
            ->prependStylesheet($this->basePath() . '/admin-public/css/style.css')
            ->prependStylesheet($this->basePath() . '/admin-public/plugins/select2/select2.css')
            ->prependStylesheet($this->basePath() . '/admin-public/plugins/font-awesome-4.1.0/css/font-awesome.css')
            ->prependStylesheet($this->basePath() . '/admin-public/plugins/bootstrap/bootstrap.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendScript('
                tinymce.init({
                    selector: "textarea"
                });', $type = 'text/javascript')
            // Include all compiled plugins (below), or include individual files as needed 
            ->prependFile($this->basePath() . '/admin-public/plugins/tinymce/tinymce.min.js')
            ->prependFile($this->basePath() . '/admin-public/plugins/bootstrap/bootstrap.min.js')
            // jQuery (necessary for Bootstrap's JavaScript plugins) 
            ->prependFile($this->basePath() . '/admin-public/plugins/jquery-ui/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/admin-public/plugins/jquery/jquery-2.1.0.min.js')
        ; ?>

    </head>
    <body>
    <!--Start Header-->
    <header class="navbar">
        <div class="container-fluid expanded-panel">
            <div class="row">
                <div id="logo" class="col-xs-12 col-sm-2">
                    <a href="index.html">FRYDAY Admin</a>
                </div>
                <div id="top-panel" class="col-xs-12 col-sm-10">
                    <div class="row">
                        <div class="col-xs-8 col-sm-4">
                            <a href="#" class="show-sidebar">
                                <i class="fa fa-bars"></i>
                            </a>
                        </div>
                        <div class="col-xs-4 col-sm-8 top-panel-right">
                            <ul class="nav navbar-nav pull-right panel-menu">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle account" data-toggle="dropdown">
                                        <div class="avatar">
                                            <img src="/img/anders_avatar.jpg" class="img-rounded" alt="avatar" />
                                        </div>
                                        <i class="fa fa-angle-down pull-right"></i>
                                        <div class="user-mini pull-right">
                                            <span class="welcome">Welcome,</span>
                                            <span>Anders Östlund</span>
                                        </div>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-user"></i>
                                                <span>Profile</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="ajax/page_messages.html" class="ajax-link">
                                                <i class="fa fa-envelope"></i>
                                                <span>Messages</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="ajax/gallery_simple.html" class="ajax-link">
                                                <i class="fa fa-picture-o"></i>
                                                <span>Albums</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="ajax/calendar.html" class="ajax-link">
                                                <i class="fa fa-tasks"></i>
                                                <span>Tasks</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-cog"></i>
                                                <span>Settings</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fa fa-power-off"></i>
                                                <span>Logout</span>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!--End Header-->

    <!--Start Container-->
    <div id="main" class="container-fluid">
        <div class="row">
            <div id="sidebar-left" class="col-xs-2 col-sm-2">
                <?php // echo $this->navigation('navigation')->menu()->setUlClass('nav main-menu')->escapeLabels(false); ?>
                <?php 
                    // echo $this->navigation('admin_main_navigation')->menu()->setUlClass('nav main-menu')->escapeLabels(false); 
                    echo $this->navigation('secondary_navigation')->menu()->setPartial(array('admin/partials/menu.phtml', 'default'))->render(); 
                    // echo $this->navigation('secondary_navigation')->menu()->setPartial(array('admin/partials/menu.phtml', 'default'))->renderSubMenu(null, 'sidebar', 0);                
                ?> 
            </div>
            <div id="content" class="col-xs-12 col-sm-10">
                <!--Start Breadcrumb-->
                <div class="row">
                    <div id="breadcrumb" class="col-xs-12">
                        <ol class="breadcrumb">
                            <li><a href="index.html">Home</a></li>
                            <li><a href="#">Dashboard</a></li>
                        </ol>
                    </div>
                </div>
                <!--End Breadcrumb-->

                <!-- Start Main Content -->
                <?php echo $this->content; ?>
                <!-- End Main Content  -->
            </div>
        </div>
    </div>
    <!--End Container-->
    </body>
</html>
