            
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <!--Table Search v2-->
                    <?php $form->setAttribute('action', $this->url('administrator/default', array('controller' => 'subscriber', 'action' => 'csv-parse-file')))->prepare(); ?>
                    <?php echo $this->form()->openTag($form); ?>
                    <!-- <form action="" class="sky-form"> -->
                    <header>CSV Parser</header>
                    
                    <fieldset>
                        <section class="col-md-6">
                            <?php echo $this->formLabel($this->form->get('city')); ?>
                            <label class="select">
                                <?php echo $this->formSelect($this->form->get('city')); ?>
                                <i></i>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('city')); ?>
                        </section>

                        <section class="col-md-12">
                                <?php echo $this->formLabel($this->form->get('csvFile')); ?>
                                <label for="csvFile" class="input input-file">
                                    <div class="button">
                                        <?php echo $this->formFile($this->form->get('csvFile')); ?>
                                        Browse
                                    </div>
                                    <input readonly="" type="text">
                                    <?php //echo $this->formFile($this->form->get('profileImage')); ?>
                                </label>
                                <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('csvFile')); ?>
                        </section>


                    </fieldset>
                    
                    <footer>
                        <button type="submit" class="btn-u">Submit</button>
                        <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">Back</button>
                    </footer>
                <!-- </form> -->
                    <?php echo $this->form()->closeTag($form); ?>
                    <!--End Table Search v2-->
                </div>
                <!--End Profile Body-->
            </div>