<div class="profile container content">
    	<div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <img class="img-responsive profile-img margin-bottom-20" src="<?php echo '/uploads/users' . DIRECTORY_SEPARATOR . $this->identity()->getId() . DIRECTORY_SEPARATOR . 'square264x264_' . $this->identity()->getImage(); ?>" alt="">
                <?php echo $this->navigation('admin_navigation')->menu()->setUlClass('list-group sidebar-nav-v1 margin-bottom-40')->setAddClassToListItem(true)->escapeLabels(false); ?>
                <hr>
            </div>
            <!--End Left Sidebar-->
            
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <!--Table Search v2-->
                    <div>
                    <a href="<?php echo $this->url('administrator/default', array('controller' => 'subscriber', 'action' => 'create' )); ?>" class="btn-u btn-brd btn-brd-hover btn-u-default btn-u-xs margin-bottom-20">Add Subscriber</a>
                    <a href="<?php echo $this->url('administrator/default', array('controller' => 'subscriber', 'action' => 'csv-parse' )); ?>" class="btn-u btn-brd btn-brd-hover btn-u-red btn-u-xs margin-bottom-20">CSV Parser</a>
                    </div>
                    <div class="table-search-v2 margin-bottom-20">
                        <div class="table-responsive">

                            <?php if(count($flashMessages)) : ?>
                            <div class="alert alert-danger fade in">
                                Subscribers with following email already exist and did not add to Fryday database: <br> <br>
                                <?php foreach ($flashMessages as $msg) : ?>
                                <?php echo $msg; ?> <br>
                                <?php endforeach; ?>
                            </div>
                            <?php endif; ?>

                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th class="hidden-sm">Name</th>
                                        <th>Status</th>
                                        <th>Contacts</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($subscribers as $subscriber): ?>
                                    <tr>
                                        <td class="td-width">
                                            <h3><a href="#"><?php echo $subscriber->getFirstName(); ?></a></h3>
                                            <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id commodo lacus. Fusce non malesuada ante. Donec vel arcu.</p>
                                            <small class="hex">Joined February 28, 2014</small> -->
                                        </td>
                                        <td>

                                        </td>
                                        <td>
                                            <span><a href="#"><?php echo $subscriber->getEmail(); ?></a></span>
                                            <span><a href="#"><?php echo $subscriber->getCity()->getName(); ?></a></span>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>    
                    </div>
                    <!--End Table Search v2-->
                </div>
                <!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div>