<div class="profile container content">
    	<div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <img class="img-responsive profile-img margin-bottom-20" src="<?php echo '/uploads/users' . DIRECTORY_SEPARATOR . $this->identity()->getId() . DIRECTORY_SEPARATOR . 'square264x264_' . $this->identity()->getImage(); ?>" alt="">
                <?php echo $this->navigation('admin_navigation')->menu()->setUlClass('list-group sidebar-nav-v1 margin-bottom-40')->setAddClassToListItem(true)->escapeLabels(false); ?>
                <hr>
            </div>
            <!--End Left Sidebar-->
            
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <div>
                        <?php if(count($flashMessages)) : ?>
                            <div class="alert alert-success fade in">
                                <?php foreach ($flashMessages as $msg) : ?>
                                <?php echo $msg; ?> <br>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div>
                    <a href="<?php echo $this->url('administrator/default', array('controller' => 'subscriber', 'action' => 'create' )); ?>" class="btn-u btn-brd btn-brd-hover btn-u-default btn-u-xs margin-bottom-20">Add Subscriber</a>
                    <a href="<?php echo $this->url('administrator/default', array('controller' => 'subscriber', 'action' => 'csv-parse-text' )); ?>" class="btn-u btn-brd btn-brd-hover btn-u-red btn-u-xs margin-bottom-20">CSV Text Parser</a>
                    <a href="<?php echo $this->url('administrator/default', array('controller' => 'subscriber', 'action' => 'csv-parse-file' )); ?>" class="btn-u btn-brd btn-brd-hover btn-u-red btn-u-xs margin-bottom-20">CSV File Parser</a>
                    </div>
                    <?php //echo $this->paginationControl($this->paginator,
                                    //'Sliding', // All, Elastic, Jumping, Sliding
                                    //'search_pagination.phtml', array('route' => 'administrator/paginator')); ?>
                    <div class="table-search-v2 margin-bottom-20">
                        <div class="table-responsive">
                            <?php $paging = $this->paginationHelper($pagedSubscribers, $page, '/admin/subscriber/', 10); ?>
                            <!-- <h1>Users</h1>
                            <table class="table table-striped">
                                <thead>    <tr>
                                    <th>Name</th>
                                    <th>Username</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php //foreach($pagedSubscribers as $subscriber) { ?>
                                    <tr>
                                        <td><?php //echo $this->escapeHtml($subscriber->firstName) . ' ' . $this->escapeHtml($subscriber->lastName); ?></td>
                                        <td><?php //echo $this->escapeHtml($subscriber->username); ?></td>
                                    </tr>
                                <?php //} ?>
                                </tbody>
                            </table> -->
                            <div class="paging">
                                <?php echo $paging; ?>
                            </div>
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>City</th>
                                        <th>Name</th>
                                        <th>Company</th>
                                        <th>Position</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($pagedSubscribers as $subscriber): ?>
                                    <tr>
                                        <td><?php echo $subscriber->getEmail();?></td>
                                        <td><?php echo $subscriber->getCity()->getName();?></td>
                                        <td><?php echo $subscriber->getFirstName();?> <?php echo $subscriber->getLastName();?></td>
                                        <td><?php echo $subscriber->getCompany();?></td>
                                        <td><?php echo $subscriber->getPosition();?></td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>    
                    </div>
                    <!--End Table Search v2-->
                    <?php //echo $this->paginationControl($this->paginator,
                            //        'Sliding', // All, Elastic, Jumping, Sliding
                            //        'search_pagination.phtml', array('route' => 'administrator/paginator')); ?>
                </div>
                <!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div>