<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">About</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">About</li>
        </ul>
    </div>
</div>

<div class="container content">		
    	<div class="row margin-bottom-40">
            <div class="title-box-v2">
                <!-- <h2>About <span class="color-green">Unify</span></h2> -->
                <p>Fryday is an international network of cosmopolitan professionals present in 30 cities in 20+ countries and has 150k+ registered members.  Fryday offers unique networking opportunities in a truly international environment.</p>
            </div>
        	<div class="col-md-6 md-margin-bottom-40">
                <!-- <p>Fryday is an international network of cosmopolitan professionals present in 30 cities in 20+ countries and has 150k+ registered members.  Fryday offers unique networking opportunities in a truly international environment.</p> -->
                <p>Fryday’s mission is to further business and social relationships by combing real life social and professional events with online platforms.</p>
                <p>The Fryday community is composed of cosmopolitan professional crowd, business owners, government officials and media representatives. Using both, offline and online platforms, the Fryday network works to bring people together so that they can make new contacts as well as sustain those already existing.</p>

                <p>Fryday offers speakers:</p>
                <ul class="list-unstyled">
                    <li><i class="fa fa-check color-green"></i> Senior crowd</li>
                    <li><i class="fa fa-check color-green"></i> Large number of guests</li>
                    <li><i class="fa fa-check color-green"></i> Professional and extensive online promotion</li>
                    <li><i class="fa fa-check color-green"></i> Media presence at the event</li>
                </ul>
            </div>

        	<div class="col-md-6 md-margin-bottom-40">
                <div class="responsive-video">
                	<iframe src="//www.youtube.com/embed/YT7UYJJdUQY" frameborder="0" allowfullscreen></iframe>
                   	<!--  <iframe src="http://player.vimeo.com/video/9679622" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" frameborder="0"></iframe>  -->
                </div>
            </div>
        </div><!--/row-->

    	
    </div>