<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Franchise</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Franchise</li>
        </ul>
    </div>
</div>

<div class="container content">		
    	<div class="row margin-bottom-40">
        	<div class="col-md-6 md-margin-bottom-40">
                <p>Fryday is an international network of cosmopolitan professionals present in 30 cities in 20+ countries and has 150k+ registered members. Fryday offers unique networking opportunities in a truly international environment.</p>
                <p>Fryday operates as a franchise, which means that an independent representative that manages the group in accordance with Fryday’s concept runs each of Fryday’s local communities. </p>
                <p>Fryday’s Representatives have a unique position in the local community being extremely well connected and well known persons. Fryday’s Representatives also has a very high social status and a great opportunity to make good money from what they enjoy best – networking and social life.</p>
                <p>Key benefits of Fryday Franchisees:</p>
                <ul class="list-unstyled">
                    <li><i class="fa fa-check color-green"></i> Superb local network at all levels.</li>
                    <li><i class="fa fa-check color-green"></i> Freedom of operations</li>
                    <li><i class="fa fa-check color-green"></i> Great financial reward</li>
                    <li><i class="fa fa-check color-green"></i> Social standing</li>
                    <li><i class="fa fa-check color-green"></i> Fun!</li>
                </ul>
                <p>Fryday is expanding on new markets. Maybe you are the right person to become a Fryday Representative?</p>
                <p>Are you?</p>
                <ul class="list-unstyled">
                    <li><i class="fa fa-check color-green"></i> Hard working?</li>
                    <li><i class="fa fa-check color-green"></i> Driven?</li>
                    <li><i class="fa fa-check color-green"></i> Social?</li>
                    <li><i class="fa fa-check color-green"></i> A leader?</li>
                    <li><i class="fa fa-check color-green"></i> Detailed oriented?</li>
                    <li><i class="fa fa-check color-green"></i> Capable of interacting with all kinds of people?</li>
                </ul>
                <p>Apply to become a Fryday Representative by email info@fryday.net. Please tell us who you are and what city or cities you are interested in.</p>
                <p>Learn more about Fryday from videos from previous events.</p>
                <br>
            </div>

        	<div class="col-md-6 md-margin-bottom-40">
                <div class="responsive-video">
                	<iframe src="//www.youtube.com/embed/Nyw9np-z53w" frameborder="0" allowfullscreen></iframe>
                   	<!--  <iframe src="http://player.vimeo.com/video/9679622" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" frameborder="0"></iframe>  -->
                </div>
            </div>
        </div><!--/row-->

    	
    </div>