<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Media</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Media</li>
        </ul>
    </div>
</div>

<div class="container content">     
        <div class="row margin-bottom-40">
            <div class="col-md-6 md-margin-bottom-40">
                <p>Fryday is an international network of cosmopolitan professionals present in 30 cities in 20+ countries and has 150k+ registered members.  Fryday offers unique networking opportunities in a truly international environment. </p>
                <p>Media and Fryday has a common interest for co-operating. Fryday proved nice content, interesting people and branding for the media. The media circulates information about Fryday to a wide audience and strengthen Fryday’s brand.</p>
                <p>Key Values: Well known speakers, prominent guests. High absolute number of contacts in databases and social media.</p>
            </div>

            <div class="col-md-6 md-margin-bottom-40">
                <div class="responsive-video">
                    <iframe src="//www.youtube.com/embed/YT7UYJJdUQY" frameborder="0" allowfullscreen></iframe>
                    <!--  <iframe src="http://player.vimeo.com/video/9679622" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" frameborder="0"></iframe>  -->
                </div>
            </div>
        </div><!--/row-->

        
    </div>