<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Member</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Member</li>
        </ul>
    </div>
</div>

<div class="container content">		
    	<div class="row margin-bottom-40">
        	<div class="col-md-6 md-margin-bottom-40">
                <p>Members visit Fryday primarily to socialize, meet new people and share information with each other and companies present.</p>
                <p>Most of Fryday’s guests are in business and many are owners and seniors. Roughly 20 per cent of guests are expatriates.</p>
                <p>Members appreciate the free format of Fryday’s events and enjoy participating at a time of their choosing and the opportunity to bring guests.</p>
                
            </div>

        	<div class="col-md-6 md-margin-bottom-40">
                <div class="responsive-video">
                	<iframe src="//www.youtube.com/embed/hy6nxFMO104" frameborder="0" allowfullscreen></iframe>
                   	<!--  <iframe src="http://player.vimeo.com/video/9679622" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" frameborder="0"></iframe>  -->
                </div>
            </div>
        </div><!--/row-->

    	
    </div>