<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Venues</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Venues</li>
        </ul>
    </div>
</div>
<!-- <div class="breadcrumbs-v3 margin-bottom-30">
        <div class="container">
            <h1 class="pull-left">Search Table</h1>
            <ul class="pull-right breadcrumb">
                <li><a href="index.html">Home</a></li>
                <li><a href="">Page</a></li>
                <li class="active">Search table</li>
            </ul>
        </div>
    </div> -->
<div class="container content">		
    	<div class="row margin-bottom-40">
        	<div class="col-md-6 md-margin-bottom-40">
                <p>
                	Fryday is an international network of cosmopolitan professionals present in 30 cities in 20+ countries and has 150k+ registered members.  Fryday offers unique networking opportunities in a truly international environment. 
                </p>
                <p>
                	Venues benefit from the large number of guests that Fryday brings. Fryday’s extensive promotion of events adds additional value to venues as their names and brands are spread through digital media and by Fryday’s partners. Many of Fryday’s guests also represent companies and purchasing power that is very likely to become regular clients of the venue. A good Fryday venue is located down-town, is modern, trendy and up-market. Restaurants, hotels and night-clubs are most common and good co-operation and understanding from the side of the venue management is key to success. 
                </p>
                <p>
                	Fryday offers venues:
                </p>
                <ul class="list-unstyled">
                    <li><i class="fa fa-check color-green"></i> Sales at the event</li>
                    <li><i class="fa fa-check color-green"></i> Branding and advertisement</li>
                    <li><i class="fa fa-check color-green"></i> Returning business from guests and companies they represent.</li>
                </ul>
                <br>

                <!-- Blockquotes -->
<!--                 <blockquote class="hero-unify">
                    <p>Award winning digital agency. We bring a personal and effective approach to every project we work on, which is why.</p>
                    <small>CEO Jack Bour</small>
                </blockquote> -->
            </div>

        	<div class="col-md-6 md-margin-bottom-40">
                <div class="responsive-video">
                	<iframe src="//www.youtube.com/embed/hy6nxFMO104" frameborder="0" allowfullscreen></iframe>
                   <!--  <iframe src="http://player.vimeo.com/video/9679622" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" frameborder="0"></iframe>  -->
                </div>
            </div>
        </div><!--/row-->

    	<!-- Our Clients -->
        <div id="clients-flexslider" class="flexslider home clients">
            <div class="headline"><h2>Venues</h2></div>    
            
        <div style="overflow: hidden; position: relative;" class="flex-viewport"><ul style="width: 3400%; transition-duration: 0.6s; transform: translate3d(-253.333px, 0px, 0px);" class="slides">
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/hp_grey.png" alt=""> 
                        <img src="/frontend/img/clients/hp.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/igneus_grey.png" alt=""> 
                        <img src="/frontend/img/clients/igneus.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/vadafone_grey.png" alt=""> 
                        <img src="/frontend/img/clients/vadafone.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/walmart_grey.png" alt=""> 
                        <img src="/frontend/img/clients/walmart.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/shell_grey.png" alt=""> 
                        <img src="/frontend/img/clients/shell.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/natural_grey.png" alt=""> 
                        <img src="/frontend/img/clients/natural.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/aztec_grey.png" alt=""> 
                        <img src="/frontend/img/clients/aztec.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/gamescast_grey.png" alt=""> 
                        <img src="/frontend/img/clients/gamescast.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/cisco_grey.png" alt=""> 
                        <img src="/frontend/img/clients/cisco.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/everyday_grey.png" alt=""> 
                        <img src="/frontend/img/clients/everyday.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/cocacola_grey.png" alt=""> 
                        <img src="/frontend/img/clients/cocacola.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/spinworkx_grey.png" alt=""> 
                        <img src="/frontend/img/clients/spinworkx.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/shell_grey.png" alt=""> 
                        <img src="/frontend/img/clients/shell.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/natural_grey.png" alt=""> 
                        <img src="/frontend/img/clients/natural.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/gamescast_grey.png" alt=""> 
                        <img src="/frontend/img/clients/gamescast.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/everyday_grey.png" alt=""> 
                        <img src="/frontend/img/clients/everyday.png" class="color-img" alt="">
                    </a>
                </li>
                <li style="width: 125.667px; float: left; display: block;">
                    <a href="#">
                        <img src="/frontend/img/clients/spinworkx_grey.png" alt=""> 
                        <img src="/frontend/img/clients/spinworkx.png" class="color-img" alt="">
                    </a>
                </li>
            </ul></div></div><!--/flexslider-->
        <!-- //End Our Clients -->
    </div>