           
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <!--Table Search v2-->
                    <?php $form->setAttribute('action', $this->url('administrator/default', array('controller' => 'newsletter', 'action' => 'create', 'id' => $event->getId())))->prepare(); ?>
                    <?php echo $this->form()->openTag($form); ?>
                    <!-- <form action="" class="sky-form"> -->
                    <header>Create Newsletter</header>
                    
                    <fieldset>
                        <section>
                            <?php echo $this->formLabel($this->form->get('partner1')); ?>
                            <label class="select">
                                <?php echo $this->formSelect($this->form->get('partner1')); ?>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('partner1')); ?>
                        </section>

                        <section>
                            <?php echo $this->formLabel($this->form->get('partner2')); ?>
                            <label class="select">
                                <?php echo $this->formSelect($this->form->get('partner2')); ?>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('partner2')); ?>
                        </section>

                        <section>
                            <?php echo $this->formLabel($this->form->get('partner3')); ?>
                            <label class="select">
                                <?php echo $this->formSelect($this->form->get('partner3')); ?>
                                <i></i>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('partner3')); ?>
                        </section>

                    </fieldset>
                    
                    <footer>
                        <button type="submit" class="btn-u">Create</button>
                        <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">Back</button>
                    </footer>
                <!-- </form> -->
                    <?php echo $this->form()->closeTag($form); ?>
                    <!--End Table Search v2-->
                </div>
                <!--End Profile Body-->
            </div>