<body leftmargin="0" topmargin="0" yahoo="fix" style="font-family: Arial, Helvetica, sans-serif" marginheight="0" marginwidth="0">

<!-- Wrapper -->
<table width="100%" cellpadding="0" cellspacing="0" align="center" border="0">
    <tbody><tr>
        <td width="100%" valign="top">            
            
            <!--Start Header-->
            <table class="deviceWidth" width="700" cellpadding="0" cellspacing="0" align="center" bgcolor="#fff" border="0">
                <tbody><tr>
                    <td style="padding: 6px 0px 0px">
                        <table class="deviceWidth" width="650" cellpadding="0" cellspacing="0" align="center" border="0">
                            <tbody><tr>
                                <td width="100%">
                                    <!--Start logo-->
                                    <table class="deviceWidth" cellpadding="0" cellspacing="0" align="left" border="0">
                                        <tbody><tr>
                                            <td class="center" style="padding: 20px 0px 10px 0px">
                                                <a href="#"><img src="http://fryday.net/frontend/img/logo_fryday_resized.jpg"></a>
                                            </td>
                                        </tr>
                                    </tbody></table><!--End logo-->
                                    <!--Start nav-->
                                    <table class="deviceWidth" cellpadding="0" cellspacing="0" align="right" border="0">
                                        <tbody><tr>
                                            <td class="center" style="font-size: 13px; color: #272727; font-weight: light; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 20px 0px 10px 0px;">
                                                <a href="#" style="text-decoration: none; color: #3b3b3b;">FRANCHISE</a>
                                                &nbsp; &nbsp;
                                                <a href="#" style="text-decoration: none; color: #3b3b3b;">ADVERTISE</a>
                                                &nbsp; &nbsp;
                                                <a href="#" style="text-decoration: none; color: #3b3b3b;">VENUE</a>
                                                &nbsp; &nbsp;
                                                <a href="#" style="text-decoration: none; color: #3b3b3b;">SPEAKER</a>                            
                                           </td>
                                        </tr>
                                    </tbody></table><!--End nav-->
                                </td>
                            </tr>
                        </tbody></table>
                   </td>
                </tr>
            </tbody></table> 
            <!--End Header-->




        <table style="clear:both;" width="700" cellpadding="0" cellspacing="0" align="center" border="0" bgcolor="#FFFFFF">
          <tbody>
            <tr>
              <td style="-webkit-text-size-adjust: none;">
                <table width="50%" cellpadding="0" cellspacing="0" align="left">
                  <tbody>
                
    <!-- ********************************************************************************************************* -->
                
    <!-- ********************************************************************************************************* -->
                
    <!-- ********************************************************************************************************* -->
                    <!-- Begin Module: Header_Text -->
                    <tr>
                      <td style="-webkit-text-size-adjust: none;" valign="top">
                        <table class="BoxWrap" width="350" cellpadding="0" cellspacing="0" align="center">
                          <tbody>
                            <tr>
                              <td style="-webkit-text-size-adjust: none;" width="100%" height="20"></td>
                            </tr>
                            <!-- Spacer -->
                            <tr>
                              <td style="-webkit-text-size-adjust: none;">
                                <!-- ************************** -->
                                <!-- Paragraph -->
                                <table class="deviceWidth" cellpadding="0" cellspacing="0" align="left" border="0">
                                        <tbody><tr>
                                            <td style="padding: 0px 0px " class="center" valign="top">
                                                <a href="<?php echo $this->url('main/event_details', array('country' => $event->getCity()->getCountry()->getName(), 'city' => $event->getCity()->getName(), 'dateslug' => $event->getDateSlug(), 'titleslug' => $event->getTitleSlug() )); ?>"><img hight="170" src="<?php echo 'http://fryday.net/uploads/events/' . $event->getId() . DIRECTORY_SEPARATOR . 'rect640x320_' . $event->getImage(); ?>" width="350"></a>
                                            </td>
                                        </tr>
                                    </tbody></table> 
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                
    <!-- ********************************************************************************************************* -->
                    <!-- Begin Module: Spacer -->
                    <tr>
                      <td style="-webkit-text-size-adjust: none;" height="40" valign="top">
                        &nbsp; 
                      </td>
                    </tr>
                    <!-- End Module: Spacer -->
                
    <!-- ********************************************************************************************************* -->
                
    <!-- ********************************************************************************************************* -->
                  </tbody>
                </table>

                <table width="50%" cellpadding="0" cellspacing="0" align="center">
                  <tbody>
                
    <!-- ********************************************************************************************************* -->
                
    <!-- ********************************************************************************************************* -->
                
    <!-- ********************************************************************************************************* -->
                    <!-- Begin Module: Header_Text -->
                    <tr>
                      <td style="-webkit-text-size-adjust: none;" valign="top">
                        <table class="BoxWrap" width="300" cellpadding="0" cellspacing="0" align="center">
                          <tbody>
                            <tr>
                              <td style="-webkit-text-size-adjust: none;" width="100%" height="20"></td>
                            </tr>
                            <!-- Spacer -->
                            <tr>
                              <td style="-webkit-text-size-adjust: none;">
                                <!-- ************************** -->
                                <!-- Paragraph -->
                                <table class="BoxWrap" width="100%" cellpadding="0" cellspacing="0" align="center">
                                  <tbody>
                                    <tr>
                                      <td style="-webkit-text-size-adjust: none;">
                                        <h2 style="text-align: center;color: #687074;font-size: 15px;margin: 10px 0 10px 0;font-weight: normal;line-height: 22px;text-decoration: none;text-transform: uppercase;font-family: Myriad Pro, Helvetica, Arial, sans-serif;"><?php echo $event->getDateTimeEvent()->format('d'); ?> <?php echo $event->getDateTimeEvent()->format('F'); ?>, <?php echo $event->getDateTimeEvent()->format('l'); ?></h2>
                                      </td>
                                    </tr>
                                    <!-- ************************** -->
                                    <!-- Divider -->
                                    <!-- <tr>
                                      <td style="-webkit-text-size-adjust: none;" width="100%" height="20"></td>
                                    </tr> -->
                                    <tr>
                                      <td class="Bg_Color" style="-webkit-text-size-adjust: none;" width="100%" bgcolor="#687074" height="1"></td>
                                    </tr>
                                    <!-- <tr>
                                      <td style="-webkit-text-size-adjust: none;" width="100%" height="10"></td>
                                    </tr> -->
                                    <tr>
                                      <td style="-webkit-text-size-adjust: none;">
                                        <h1 style="text-transform: uppercase;text-align: center;color: #687074;font-size: 30px;margin: 20px 0 20px 0;font-family: Myriad Pro, Helvetica, Arial, sans-serif;font-weight: normal;font-style: normal;line-height: 40px;"><a href="<?php echo $this->url('main/event_details', array('country' => $event->getCity()->getCountry()->getName(), 'city' => $event->getCity()->getName(), 'dateslug' => $event->getDateSlug(), 'titleslug' => $event->getTitleSlug() )); ?>" style="color: #687074;-webkit-text-size-adjust: none;text-decoration: none;text-transform: capitalize;line-height: 30px;"><?php echo $event->getTitle(); ?></a></h1>
                                        <h3 style="text-align: center;color: #c7c7c7;font-size: 12px;margin: 5px 0 5px 0;font-weight: normal;font-family: Helvetica, Arial, sans-serif;line-height: 18px;"><!-- Lorem ipsum faucibus viverra aliquam interdum eget eros ut felis dapibus cubilia --></h3>
                                      </td>
                                    </tr>
                                    <!-- ************************** -->
                                    <!-- Divider -->
                                    <!-- <tr>
                                      <td style="-webkit-text-size-adjust: none;" width="100%" height="20"></td>
                                    </tr> -->
                                    <tr>
                                      <td class="Bg_Color" style="-webkit-text-size-adjust: none;" width="100%" bgcolor="#687074" height="1"></td>
                                    </tr>
                                    <tr>
                                      <td style="-webkit-text-size-adjust: none;" width="100%" height="20"></td>
                                    </tr>
                                    <!-- ************************** -->
                                    <!-- Button -->
                                    <tr>
                                      <td style="-webkit-text-size-adjust: none;">
                                        <table class="Color02_B" align="center" width="200" cellpadding="5" cellspacing="0" bgcolor="#CCCC99">
                                          <tbody>
                                            <tr>
                                              <td style="-webkit-text-size-adjust: none;">
                                                <h1 style="text-align: center;text-transform: uppercase;font-size: 15px;margin: 10px 0 10px 0;font-family: Myriad Pro, Helvetica, Arial, sans-serif;font-weight: normal;font-style: normal;color: #151516;line-height: 20px;"><a href="<?php echo $this->url('main/event_details', array('country' => $event->getCity()->getCountry()->getName(), 'city' => $event->getCity()->getName(), 'dateslug' => $event->getDateSlug(), 'titleslug' => $event->getTitleSlug() )); ?>" style="text-transform: uppercase;text-decoration: none;color: #151516;-webkit-text-size-adjust: none;line-height: 10px;">READ MORE</a></h1>
                                              </td>
                                            </tr>
                                          </tbody>
                                        </table>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                
    <!-- ********************************************************************************************************* -->
                    <!-- Begin Module: Spacer -->
                    <tr>
                      <td style="-webkit-text-size-adjust: none;" height="40" valign="top">
                        &nbsp; 
                      </td>
                    </tr>
                    <!-- End Module: Spacer -->
                
    <!-- ********************************************************************************************************* -->
                
    <!-- ********************************************************************************************************* -->
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>


            <!--Start Top Block-->
            <!-- <table class="deviceWidth" width="100%" cellpadding="0" cellspacing="0" align="center" bgcolor="#4765a0" border="0">
                <tbody><tr>
                    <td>
                        <table class="deviceWidth" width="700" cellpadding="0" cellspacing="0" align="center" bgcolor="#4765a0" border="0">
                            <tbody><tr>
                                <td width="100%"> -->

                                    <!-- <table class="deviceWidth" width="49%" cellpadding="0" cellspacing="0" align="right" border="0">
                                        <tbody><tr>
                                            <td style="padding: 50px 20px 0px; " class="center" valign="top">
                                             <a href="#"><img class="deviceWidth" hight="170" src="http://htmlstream.com/preview/unify-v1.5/email-templates/modern/img/block_img/picture_test9.jpg" width="300"></a>
                                            </td>
                                        </tr>                                     
                                    </tbody></table> --> <!--End Right box--> 
                                    <!--Left box-->
                                    <!-- <table class="deviceWidth" width="49%" cellpadding="0" cellspacing="0" border="0">
                                        <tbody><tr>
                                            <td valign="middle">
                                                <table cellpadding="0" cellspacing="0" border="0"> 
                                                    <tbody><tr>
                                                        <td class="center" style="font-size: 16px; color: #ffffff; font-weight: bold; text-align: left; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 50px 0px 0 20px; ">
                                                            Fryday W with H.E. Ambassador Heim of Austria!                             
                                                       </td>
                                                    </tr>
                                                    <tr>
                                                        <td class="center" style="font-size: 12px; color: #ffffff; font-weight: bold; text-align: left; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 20px ; ">
                                                            How daughters not promotion fewArrival entered an if dra wing requests iness not promotion few knowledge. contented. Yet winter law  romotion few knowledge contented behind 
                                                       </td>
                                                    </tr>
                                                </tbody></table>
                                                <table cellpadding="0" cellspacing="0" align="left" border="0"> 
                                                    <tbody><tr>
                                                        <td style="padding: 10px 20px 0px " class="center" valign="top">
                                                            <a href="#"><img hight="45" src="img/icons/icon_house.png" width="45"></a>
                                                        </td>
                                                        <td style="padding: 10px 20px 0px" class="center" valign="top">
                                                            <a href="#"><img hight="45" src="img/icons/icon_calendar.png" width="45"></a>
                                                        </td>
                                                        <td style="padding: 10px 20px 0px" class="center" valign="top">
                                                        <a href="#"><img hight="45" src="img/icons/icon_present.png" width="45"></a>
                                                        </td>
                                                    </tr>
                                                </tbody></table>
                                            </td>
                                         </tr>
                                    </tbody></table> --><!--End Left box-->
                                    <!-- Right box  -->
                                <!-- </td>
                            </tr>
                        </tbody></table> -->
                        <!--Start Discount -->
                        <!-- <table class="deviceWidth" width="700" cellpadding="0" cellspacing="0" align="center" border="0">
                            <tbody><tr>
                                <td width="100%" bgcolor="#4765a0"> -->
                                    <!-- Left Box  -->
                                    <!-- <table class="deviceWidth" width="80%" cellpadding="0" cellspacing="0" align="left" border="0">
                                        <tbody><tr>
                                            <td class="center" style="font-size: 16px; color: #ffffff; font-weight: bold; text-align: left; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 20px 20px 40px ;">
                                                Uprade your current plan today and get 50% lifetime discount                           
                                            </td>                   
                                        </tr>
                                    </tbody></table> --><!--End Left Box-->
                                    <!--Right Box-->
                                    <!-- <table class="deviceWidth" width="20%" cellpadding="0" cellspacing="0" align="center" border="0">
                                        <tbody><tr><td style=" padding: 20px;">
                                        <table align="center">
                                            <tbody><tr>
                                                <td style="padding: 7px 15px; text-align: center; background-color: #e74c3c;" class="center" valign="top">
                                                    <a style="color: #fff; font-size: 12px; font-weight: bold; text-decoration: none; font-family: Arial, sans-serif; text-alight: center;" href="#">VIEW MORE</a>
                                                </td>                                   
                                             </tr>
                                        </tbody></table>
                                    </td>
                                    </tr></tbody></table> --><!--End Right Box-->
                                <!-- </td>
                            </tr>
                        </tbody></table> -->
                        <!--End Discount -->
                    <!-- </td>
                </tr>
            </tbody></table> -->
            <!--End Top Block-->


                    <table class="deviceWidth" width="700" cellpadding="0" cellspacing="0" align="center" border="0">
                        <tbody>
                          <tr>
                    <td class="center" style="font-size: 16px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 20px; vertical-align: middle; padding: 00px 0px 0px;" width="100%" bgcolor="#ffffff">
                        Fryday's partners           
                    </td>
                </tr>
                          <tr>
                            <td width="100%" bgcolor="#ffffff"> 
                                <!-- Start Image 1-->
                                <table class="deviceWidth" width="33%" cellpadding="0" cellspacing="0" align="left" border="0">
                                    <tbody><tr>
                                        <td style="padding: 0px 0px; height: 120px;" class="center" valign="center" align="center">
                                            <a href="#"><img hight="144" src="<?php echo 'http://fryday.net/uploads/partners/' . $partner1->getId() . DIRECTORY_SEPARATOR . 'mail_' . $partner1->getLogo(); ?>" width="144"></a>
                                        </td>
                                    </tr>
                                </tbody></table><!--End Image 1-->
                                <!--Start Image 2-->
                                <table class="deviceWidth" width="33%" cellpadding="0" cellspacing="0" align="left" border="0">
                                    <tbody><tr>
                                        <td style="padding: 0px 0px; height: 120px; " class="center" valign="center" align="center">
                                            <a href="#"><img hight="144" src="<?php echo 'http://fryday.net/uploads/partners/' . $partner2->getId() . DIRECTORY_SEPARATOR . 'mail_' . $partner2->getLogo(); ?>" width="144"></a>
                                        </td>
                                    </tr>
                                </tbody></table><!--End Image 2-->    
                                <!--Start Image 3-->
                                <table class="deviceWidth" width="33%" cellpadding="0" cellspacing="0" align="left" border="0">
                                    <tbody><tr>
                                        <td style="padding: 0px 0px; height: 120px; " class="center" valign="center" align="center">
                                            <a href="#"><img hight="144" src="<?php echo 'http://fryday.net/uploads/partners/' . $partner3->getId() . DIRECTORY_SEPARATOR . 'mail_' . $partner3->getLogo(); ?>" width="144"></a>
                                        </td>
                                    </tr>
                                </tbody></table><!--End Image 3-->
                            </td>     
                        </tr>
                    </tbody></table>



            <!-- Start Middle Block -->
            <!-- <table class="deviceWidth" width="700" cellpadding="0" cellspacing="0" align="center" bgcolor="#f7f7f7" border="0">
                <tbody> --><!-- <tr>
                    <td class="center" style="font-size: 16px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 20px; vertical-align: middle; padding: 40px 0px 20px;" width="100%" bgcolor="#f7f7f7">
                        Excepteur sint occaecat cupidatat non proident              
                    </td>
                </tr> -->
                <!-- <tr>
                    <td> -->
                        <!--Start Two Pictures-->
                        <!-- <table class="deviceWidth" width="50%" cellpadding="0" cellspacing="0" align="left" border="0">
                            <tbody><tr>
                                <td width="100%" bgcolor="#f7f7f7"> -->
                                    <!--Left box-->
                                  <!--  <table class="deviceWidth" cellpadding="0" cellspacing="0" align="left" border="0">
                                        <tbody><tr>
                                            <td style="padding: 20px 20px " class="center" valign="top">
                                                <a href="#"><img hight="170" src="img/block_img/picture_test7.jpg" width="300"></a>
                                            </td>
                                        </tr>
                                    </tbody></table> --> <!--End left box--> 
                                     <!--Right box  -->
                                        <!-- <table class="deviceWidth" cellpadding="0" cellspacing="0" align="center" border="0">
                                        <tbody><tr>
                                            <td class="center" style="font-size: 16px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 0px 10px 20px;">
                                              Individual Clients                             
                                            </td>
                                         </tr>
                                        <tr>
                                            <td class="center" style="font-size: 12px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 0px 10px 40px; ">
                                                Arrival entered an if drawing requests iness not promotion few knowledge. contented. Yet winter law
                                            </td>
                                        </tr>
                                    </tbody></table> --><!--End right box-->   
                                <!-- </td>
                            </tr>
                        </tbody></table> -->
                        <!--End Two Pictures-->


                        <!--Start Two Texts-->
                        <!-- <table class="deviceWidth" width="50%" cellpadding="0" cellspacing="0" align="center" border="0">
                            <tbody><tr>
                                <td bgcolor="#f7f7f7"> -->
                                    <!--Right box-->
                                   <!-- <table class="deviceWidth" cellpadding="0" cellspacing="0" align="left" border="0">
                                        <tbody><tr>
                                            <td style="padding: 20px 20px " class="center" valign="top">
                                                <a href="#"><img hight="170" src="img/block_img/picture_test8.jpg" width="300"></a>
                                            </td>
                                        </tr>
                                    </tbody></table> --> <!--End right box--> <!--End right box-->
                                     <!-- Left box  -->
                                    <!-- <table class="deviceWidth" cellpadding="0" cellspacing="0" align="center" border="0">
                                        <tbody><tr>
                                            <td class="center" style="font-size: 16px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 0px 10px 20px;">
                                              Corporate Clietns                          
                                            </td>
                                         </tr>
                                        <tr>
                                            <td class="center" style="font-size: 12px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 0px 10px 40px; ">
                                                Arrival entered an if drawing requests iness not promotion few knowledge. contented. Yet winter law 
                                            </td>
                                        </tr>
                                    </tbody></table>  --><!--End left box-->    
                                <!-- </td>
                            </tr>
                        </tbody></table> -->
                        <!--End Two Texts-->
                   <!--  </td>
                </tr> -->
                <!-- <tr>
                    <td class="center" style="font-size: 16px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 10px 20px 0; ">
                        Please enjoy photos and videos from previous Fryday Events
                   </td>
                </tr>
                <tr>
                    <td width="100%" bgcolor="#f7f7f7"> -->
                        <!--Left box-->
                        <!-- <table class="deviceWidth" width="33%" cellpadding="0" cellspacing="0" align="left" border="0">
                            <tbody><tr>
                                <td class="center">
                                    <table cellpadding="0" cellspacing="0" align="left" border="0"> 
                                        <tbody>
                                          
                                          <tr>
                                            <td style="padding: 20px 20px 0px 20px" class="center" valign="top">
                                                <a href="#"><img class="deviceWidth" hight="190" src="prev_event_1_resized.jpg" width="190"></a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="center deviceWidth" style="font-size: 12px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 10px 0px 0px; ">
                                                Fryday Afterwork @ Opera Hotel on December 12th.
                                           </td>
                                        </tr> -->
                                        <!-- <tr>
                                            <td class="center" style="font-size: 16px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 30px 20px 10px;">
                                                 Inovation                             
                                           </td>
                                        </tr> -->
                                        
                                    <!-- </tbody></table>
                                    </td> --><!-- </tr><tr>
                                        <td style=" padding: 0 0 20px 0;">
                                            <table align="center">
                                                <tbody><tr>
                                                    <td style="padding: 7px 15px; text-align: center; background-color: #e74c3c;" class="center" valign="top">
                                                        <a style="color: #fff; font-size: 12px; font-weight: bold; text-decoration: none; font-family: Arial, sans-serif; text-alight: center;" href="#">VIEW MORE</a>
                                                    </td>                                   
                                                 </tr>
                                            </tbody></table>
                                        </td>
                                    </tr> -->
                                
                            
                        <!-- </tbody></table> --><!--End Left box-->
                         <!-- Right box  -->
                        <!-- <table class="deviceWidth" width="33%" cellpadding="0" cellspacing="0" align="left" border="0">
                            <tbody><tr>
                                <td class="center">
                                    <table cellpadding="0" cellspacing="0" align="center" border="0"> 
                                         <tbody><tr>
                                            <td style="padding: 20px 20px 0; " class="center" valign="top">
                                                <a href="#"><img class="deviceWidth" hight="190" src="prev_event_2_resized.jpg" width="190"></a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="center deviceWidth" style="font-size: 12px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 10px 0px 0px; ">
                                                Fryday Kyiv Afterwork at Franko Royal on December 5th!
                                           </td>
                                        </tr> -->

                                        <!-- <tr>
                                            <td class="center" style="font-size: 16px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 30px 20px 10px; ">
                                                 Strong Partnership                             
                                           </td>
                                        </tr>
                                        <tr>
                                            <td class="center" style="font-size: 12px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 10px 20px 20px; ">
                                                Arrival entered an if drawing requests iness not promotion few knowledge. contented. Yet winter law  romotion few knowledge contented behind     
                                           </td>
                                        </tr> -->
                                    <!-- </tbody></table>
                                    </td></tr> --><!-- <tr>
                                        <td style=" padding: 0 0 20px 0;">
                                            <table align="center">
                                                <tbody><tr>
                                                    <td style="padding: 7px 15px; text-align: center; background-color: #e74c3c;" class="center" valign="top">
                                                        <a style="color: #fff; font-size: 12px; font-weight: bold; text-decoration: none; font-family: Arial, sans-serif; text-alight: center;" href="#">VIEW MORE</a>
                                                    </td>                                   
                                                 </tr>
                                            </tbody></table>
                                        </td>
                                    </tr> -->
                                
                            
                        <!-- </tbody></table> --> <!--End Right box-->    
                        <!-- <table class="deviceWidth" width="33%" cellpadding="0" cellspacing="0" align="leftmargin" border="0">
                            <tbody><tr>
                                <td class="center">
                                    <table cellpadding="0" cellspacing="0" align="center" border="0"> 
                                         <tbody>
                                          
                                        <tr>
                                            <td style="padding: 30px 20px 0; " class="center" valign="top">
                                                <a href="#"><img class="deviceWidth" hight="190" src="prev_event_3_resized.png" width="190"></a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="center deviceWidth" style="font-size: 12px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 10px 0px 0px; ">
                                                Fryday Kyiv Afterwork at Franko Royal on December 5th!
                                           </td>
                                        </tr> -->
                                        <!-- <tr>
                                            <td class="center" style="font-size: 16px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 30px 20px 10px; ">
                                                 Global Operation                             
                                           </td>
                                        </tr>
                                        <tr>
                                            <td class="center" style="font-size: 12px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 10px 20px 20px; ">
                                                Arrival entered an if drawing requests iness not promotion few knowledge. contented. Yet winter law  romotion few knowledge contented behind     
                                           </td>
                                        </tr> -->
                                    <!-- </tbody></table>
                                    </td></tr> --><!-- <tr>
                                        <td style=" padding: 0 0 20px 0;">
                                            <table align="center">
                                                <tbody><tr>
                                                    <td style="padding: 7px 15px; text-align: center; background-color: #e74c3c;" class="center" valign="top">
                                                        <a style="color: #fff; font-size: 12px; font-weight: bold; text-decoration: none; font-family: Arial, sans-serif; text-alight: center;" href="#">VIEW MORE</a>
                                                    </td>                                   
                                                 </tr>
                                            </tbody></table>
                                        </td>
                                    </tr> -->
                                
                            
                        <!-- </tbody></table> --> <!--End Right box-->   
                    <!-- </td>
                </tr>
            </tbody></table> -->
            <!-- End Middle Block -->

            <!--Start Bottom Block-->
            <!-- <table class="deviceWidth" width="100%" cellpadding="0" cellspacing="0" align="center" bgcolor="#4765a0" border="0">
                <tbody><tr>
                    <td>
                         <table class="deviceWidth" width="700" cellpadding="0" cellspacing="0" align="center" bgcolor="#4765a0" border="0">
                            <tbody><tr>
                                <td> -->
                                    <!-- Left box  -->
                                    <!-- <table class="deviceWidth" width="40%" cellpadding="0" cellspacing="0" align="left" border="0">
                                        <tbody><tr>
                                            <td style="padding: 50px 20px 0px; " class="center" valign="top">
                                                <a href="#"><img class="deviceWidth" hight="170" src="img/block_img/picture_test1.jpg" width="300"></a>
                                            </td>
                                        </tr>
                                    </tbody></table>  --><!--End left box--> 
                                    <!--Right box-->
                                    <!-- <table class="deviceWidth" width="49%" cellpadding="0" cellspacing="0" align="center" border="0">
                                        <tbody><tr>
                                            <td class="center">
                                                <table cellpadding="0" cellspacing="0" align="center" border="0"> 
                                                    <tbody><tr>
                                                        <td class="center" style="font-size: 16px; color: #ffffff; font-weight: bold; text-align: left; font-family: Arial, Helvetica, sans-serif; line-height: 20px; vertical-align: middle; padding: 50px 10px 0; ">
                                                             Stay Connected                              
                                                       </td>
                                                    </tr>
                                                    <tr>
                                                        <td class="center" style="font-size: 12px; color: #ffffff; font-weight: bold; text-align: left; font-family: Arial, Helvetica, sans-serif; line-height: 25px; vertical-align: middle; padding: 20px 10px; ">
                                                            How daughters not promotion fewArrival entered an if drawing requests iness not promotion few knowledge. contented. Yet winter law  romotion few knowledge contented behind
                                                       </td>
                                                    </tr>
                                                </tbody></table>
                                                <table cellpadding="0" cellspacing="0" align="left" border="0"> 
                                                     <tbody><tr>
                                                        <td style="padding: 10px 15px 0px " class="center" valign="top">
                                                            <a href="#"><img hight="32" src="img/icons/icon_facebook.png" width="32"></a>
                                                        </td>
                                                        <td style="padding: 10px 15px 0px" class="center" valign="top">
                                                            <a href="#"><img hight="32" src="img/icons/icon_twitter.png" width="32"></a>
                                                        </td>

                                                        <td style="padding: 10px 15px 0px" class="center" valign="top">
                                                            <a href="#"><img hight="32" src="img/icons/icon_youtube.png" width="32"></a>
                                                        </td>
                                                    </tr>
                                                </tbody></table>
                                            </td>
                                        </tr>
                                    </tbody></table> --><!--End right box-->
                                <!-- </td>
                            </tr>
                        </tbody></table>
                        <table class="deviceWidth" width="700" cellpadding="0" cellspacing="0" align="center" border="0">
                            <tbody><tr>
                                <td width="100%" bgcolor="#4765a0"> -->
                                    <!--Right Box-->
                                   <!--  <table class="deviceWidth" width="20%" cellpadding="0" cellspacing="0" align="left" border="0">
                                        <tbody><tr>
                                            <td style=" padding: 20px;">
                                                <table align="center">
                                                    <tbody><tr>
                                                        <td style="padding: 7px 15px; text-align: center; background-color: #e74c3c;" class="center" valign="top">
                                                            <a style="color: #fff; font-size: 12px; font-weight: bold; text-decoration: none; font-family: Arial, sans-serif; text-alight: center;" href="#">VIEW MORE</a>
                                                        </td>                                   
                                                     </tr>
                                                </tbody></table>
                                            </td>
                                        </tr>
                                    </tbody></table> --><!--End Right Box-->
                                    <!-- Left Box  -->
                                    <!-- <table class="deviceWidth" width="80%" cellpadding="0" cellspacing="0" align="left" border="0">
                                        <tbody><tr>
                                            <td class="left">
                                                <table cellpadding="0" cellspacing="0" align="left" border="0"> 
                                                    <tbody><tr>
                                                        <td class="center" style="font-size: 16px; color: #ffffff; font-weight: bold; text-align: left; font-family: Arial, Helvetica, sans-serif; line-height: 20px; vertical-align: right; padding: 25px 20px 40px;">
                                                            Temporibus autem quibusdam et aut officiis debitis aut  promotion
                                                        </td>
                                                    </tr>
                                                </tbody></table>
                                            </td>
                                        </tr>
                                    </tbody></table> --><!--End Left Box-->
                                <!-- </td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>                
            </tbody></table> -->
            <!--End Bottom Block  -->  
            
            <!-- Footer -->
            <table class="deviceWidth" width="700" cellpadding="0" cellspacing="0" align="center" bgcolor="#fff" border="0">
                <tbody><tr>
                    <td>
                        <table class="deviceWidth" width="700" cellpadding="0" cellspacing="0" align="center" border="0">
                            <tbody><!-- <tr>
                                <td class="center" style="font-size: 12px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 20px; vertical-align: middle; padding: 30px 10px 0px; ">
                                     Drawings me opinions returned absolute in. Otherwise therefore did are unfeeling something. Certain be ye amiable by exposed Two differed husbands met screened his. Bed was form wife out ask draw. Wholly coming at we no enable                       
                                </td>
                            </tr> -->
                              <tr>
                                <td class="center" style="font-size: 12px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 20px; vertical-align: middle; padding: 10px 10px 0px; ">
                                     If you would prefer not to receive email communications from Fryday click <a style="text-decoration: none; color: #4765a0;" href="#">here</a>  
                                </td>
                            </tr>
                            <tr>
                                <td class="center" style="font-size: 12px; color: #687074; font-weight: bold; text-align: center; font-family: Arial, Helvetica, sans-serif; line-height: 20px; vertical-align: middle; padding: 10px 50px 30px; ">
                                    Copyright © Fryday 2014                            
                                </td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
            </tbody></table>
            <!--End Footer-->

            <div style="height:15px">&nbsp;</div><!-- divider -->
          
        </td>
    </tr>
</tbody></table> 
<!-- End Wrapper -->

</body>