<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Franchise</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Franchise</li>
        </ul>
    </div>
</div>

<div class="container content">		
    	<div class="row margin-bottom-40">
        	<h1>Thank you! Yor registration has been confirmed.<?php echo $token?></h1>
        </div><!--/row-->

    	
    </div>