<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Franchise</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Franchise</li>
        </ul>
    </div>
</div>

<div class="container content">		
    	<div class="row col-md-8 col-md-offset-2 margin-bottom-40">
        	<h1>Thank you! You have now signed up to receive invitations to Fryday’s events.<br>
                Please continue to fill in the below form to complete your registration.Your email has been confirmed. </h1>
        </div><!--/row-->
        <div class="row col-md-8 col-md-offset-2 margin-bottom-40">
            <?php $form->setAttribute('action', $this->url('fryday/registration', array('controller' => 'index', 'action' => 'confirm-email', 'token' => $token)))->prepare(); ?>
            <?php echo $this->form()->openTag($form); ?>
                    <header>Registration form</header>
                    
                    <fieldset>                  
                        <div class="row">
                            <section class="col col-6">
                                <label class="input">
                                    <i class="icon-prepend fa fa-user"></i>
                                    <?php echo $this->formInput($this->form->get('firstName')); ?>
                                </label>
                                <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('firstName')); ?>
                            </section>
                            <section class="col col-6">
                                <label class="input">
                                    <i class="icon-prepend fa fa-user"></i>
                                    <?php echo $this->formInput($this->form->get('lastName')); ?>
                                </label>
                                <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('lastName')); ?>
                            </section>
                        </div>
                        <div class="row">
                            <section class="col col-6">
                                <label class="input">
                                    <i class="icon-prepend fa fa-key"></i>
                                    <?php echo $this->formInput($this->form->get('password')); ?>
                                </label>
                                <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('password')); ?>
                            </section>
                            <!-- <section class="col col-6">
                                <label class="input">
                                    <i class="icon-prepend fa fa-user"></i>
                                    <?php //echo $this->formInput($this->form->get('password')); ?>
                                </label>
                            </section> -->
                        </div>
                        <div class="row">
                            <section class="col col-6">
                                <label class="input">
                                    <?php echo $this->formInput($this->form->get('city')); ?>
                                </label>
                                <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('city')); ?>
                            </section>

                            <section class="col col-6">
                                <label class="select">
                                    <?php echo $this->formSelect($this->form->get('country')); ?>
                                    <i></i>
                                </label>
                                <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('country')); ?>
                            </section>
                        </div>
                    </fieldset>
                    
                    <fieldset>
                        <div class="row">
                            <section class="col col-6">
                                <label class="input">
                                    <i class="icon-prepend fa fa-phone"></i>
                                    <?php echo $this->formInput($this->form->get('phone')); ?>
                                </label>
                                <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('phone')); ?>
                            </section>
                        </div>
                        <div class="row">
                            <section class="col col-6">
                                <label class="input">
                                    <i class="icon-prepend fa fa-facebook"></i>
                                    <?php echo $this->formInput($this->form->get('facebook')); ?>
                                </label>
                                <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('facebook')); ?>
                            </section>
                            <section class="col col-6">
                                <label class="input">
                                    <i class="icon-prepend fa fa-linkedin"></i>
                                    <?php echo $this->formInput($this->form->get('linkedin')); ?>
                                </label>
                                <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('linkedin')); ?>
                            </section>
                        </div>
                        <div class="row">
                            <section class="col col-6">
                                <label class="input">
                                    <i class="icon-prepend fa fa-twitter"></i>
                                    <?php echo $this->formInput($this->form->get('twitter')); ?>
                                </label>
                                <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('twitter')); ?>
                            </section>
                            <section class="col col-6">
                                <label class="input">
                                    <i class="icon-prepend fa fa-skype"></i>
                                    <?php echo $this->formInput($this->form->get('skype')); ?>
                                </label>
                                <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('skype')); ?>
                            </section>
                        </div>
                    </fieldset>
                    
                    <footer>
                        <button type="submit" class="btn-u">Continue</button>
                    </footer>
                <?php echo $this->form()->closeTag($form); ?>
        </div>    	
    </div>

    <script>
    $(function(){
        
        $("#member-registration-city").geocomplete()
            .bind("geocode:result", function(event, result)
            {
                console.log(result.address_components)
                // console.log(result.address_components[0].long_name);
                // console.log(result.address_components[3].long_name);

                var countryName;

                if(result.address_components.length === 4)
                {
                    countryName = result.address_components[3].long_name
                } 
                else if (result.address_components.length === 3)
                {
                    countryName = result.address_components[2].long_name
                }
                else if (result.address_components.length === 2)
                {
                    countryName = result.address_components[1].long_name
                }

                // console.log(countryName);

                $.log("Result: " + result);
                $.post("/registration/get-city-id", { country: countryName, }, function(data)
                {
                    // console.log(data.countryId);
                    // console.log(data.cityName);
                    $("#member-registration-country").val(data.countryId);
                }, 'json');

                $("#member-registration-city").val(result.address_components[0].long_name);
            })
            .bind("geocode:error", function(event, status)
            {
                $.log("ERROR: " + status);
            })
            .bind("geocode:multiple", function(event, results)
            {
                $.log("Multiple: " + results.length + " results found");
            });
        
        $("#find").click(function()
        {
            $("#member-registration-city").trigger("geocode");
        });
        
      });
    </script>