<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Event</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Event</li>
        </ul>
    </div>
</div>

<div class="content container">
            <div class="page-wrapper">
                <div class="page-content">
                    <div class="row page-row">
                        <div class="events-wrapper col-md-8 col-sm-7">
                            <?php foreach ($events as $event): ?>
                                <article class="events-item page-row has-divider clearfix">
                                    <div class="date-label-wrapper col-md-1 col-sm-2">
                                        <p class="date-label">
                                            <span class="month"><?php echo $event->getDateTimeEvent()->format('M'); ?></span>
                                            <span class="date-number"><?php echo $event->getDateTimeEvent()->format('d'); ?></span>
                                        </p>
                                    </div><!--//date-label-wrapper-->
                                    <div class="details col-md-11 col-sm-10">
                                        <h3 class="title"><a href="<?php echo $this->url('fryday/event_details', array('country' => $event->getCity()->getCountry()->getName(), 'city' => $event->getCity()->getName(), 'dateslug' => $event->getDateSlug(), 'titleslug' => $event->getTitleSlug() )); ?>"><?php echo $event->getTitle(); ?></a></h3>
                                        <p class="meta"><span class="time"><i class="fa fa-clock-o"></i><?php echo $event->getDateTimeEvent()->format('H:i'); ?></span><span class="location"><i class="fa fa-map-marker"></i><?php echo $event->getVenue()->getName(); ?>, <?php echo $event->getVenue()->getCity()->getName(); ?></a></span></p>  
                                        <p class="desc"><?php echo $event->getDescription(); ?></p>                       
                                    </div><!--//details-->
                                </article><!--//events-item-->
                            <?php endforeach; ?>
                            
                        </div><!--//events-wrapper-->
                        <aside class="page-sidebar  col-md-3 col-md-offset-1 col-sm-4 col-sm-offset-1">                    
                            <section class="widget has-divider">
                                <h3 class="title">Featured Video</h3>
                                <iframe class="iframe" src="//www.youtube.com/embed/Nyw9np-z53w" allowfullscreen="" =""="" frameborder="0"></iframe>
                            </section>
<!--                             <section class="widget has-divider">
                                <h3 class="title">Latest News</h3>
                                <article class="news-item row">       
                                    <figure class="thumb col-md-2">
                                        <img src="assets/images/news/news-thumb-1.jpg" alt="">
                                    </figure>
                                    <div class="details col-md-10">
                                        <h4 class="title"><a href="news-single.html">Morbi bibendum consectetuer vulputate sollicitudin</a></h4>
                                    </div>
                                </article>
                                <article class="news-item row">       
                                    <figure class="thumb col-md-2">
                                        <img src="assets/images/news/news-thumb-2.jpg" alt="">
                                    </figure>
                                    <div class="details col-md-10">
                                        <h4 class="title"><a href="news-single.html">Sed tincidunt urna eget turpis pretium hendrerit</a></h4>
                                    </div>
                                </article>
                                <article class="news-item row">       
                                    <figure class="thumb col-md-2">
                                        <img src="assets/images/news/news-thumb-3.jpg" alt="">
                                    </figure>
                                    <div class="details col-md-10">
                                        <h4 class="title"><a href="news-single.html">Duis scelerisque erat iaculis</a></h4>
                                    </div>
                                </article>
                                <article class="news-item row">       
                                    <figure class="thumb col-md-2">
                                        <img src="assets/images/news/news-thumb-4.jpg" alt="">
                                    </figure>
                                    <div class="details col-md-10">
                                        <h4 class="title"><a href="news-single.html">Duis scelerisque erat iaculis</a></h4>
                                    </div>
                                </article>
                            </section> -->
                        </aside>
                    </div><!--//page-row-->
                </div><!--//page-content-->
            </div><!--//page--> 
        </div>