<div style="background-position: 50% 16px;" class="search-block parallaxBg">
    <div class="container">
        <div class="col-md-6 col-md-offset-3 title-background">
            <h1>Fryday is an International Network of <br>Cosmopolitan Professionals</h2>
            <!-- <a href="<?php //echo $this->url('fryday/registration', array('controller' => 'index', 'action' => 'member-registration' )); ?>" class="btn-u btn-brd btn-brd-hover btn-u-light margin-right-5">Sign In</a> -->
            <button class="btn-u btn-brd btn-brd-hover btn-u-light btn-inversed margin-right-5" data-toggle="modal" data-target="#responsive">Sign Up</button>
                        <div style="display: none;" class="modal fade" id="responsive" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                        <h4 class="modal-title" id="myModalLabel">Sign Up Now To Receive Invitations to Fryday’s events!</h4>
                                    </div>
                                    <div class="modal-body">
                                        <div id="emailinput" class="row">
                                            <div class="col-md-12">
                                                <?php //$signupform->setAttribute('action', $this->url('administrator/default', array('controller' => 'event', 'action' => 'create-first-step')))->prepare(); ?>
                                                <?php //echo $this->form()->openTag($signupform); ?>
                                                <!-- <fieldset> -->
                                                    <!-- <section class="col-md-12"> -->
                                                        <?php //echo $this->formInput($this->signupform->get('email')); ?>
                                                        <!-- <label class="input"> -->
                                                        <?php //echo $this->FormElementErrors($this->signupform->get('email')); ?>
                                                        <!-- </label> -->
                                                        <!-- <span class="input-group-btn"> -->
                                                            <!-- <button class="btn btn-danger btn-add-user" type="submit">Add User</button> -->
                                                        <!-- </span> -->
                                                        <!-- <div id="email-errors"></div> -->
                                                    <!-- </section> -->
                                                <!-- </fieldset> -->
                                                <?php //echo $this->form()->closeTag($signupform); ?>
                                        

                                        <?php $signupform->setAttribute('action', $this->url('administrator/default', array('controller' => 'event', 'action' => 'create-first-step')))->prepare(); ?>
                                        <?php echo $this->form()->openTag($signupform); ?>
                                        <div class="input-group">
                                            <label class="input">
                                                <?php echo $this->formInput($this->signupform->get('email')); ?>
                                            </label>
                                            <!-- <input class="form-control" type="text"> -->
                                            <span class="input-group-btn">
                                                <button id="sign-up-button" type="button" class="btn btn-danger btn-add-user">SignUp</button>
                                                <!-- <button class="btn btn-danger btn-add-user" type="submit">SignUp</button> -->
                                            </span>
                                        </div>
                                        <div id="email-errors"></div>
                                        <?php echo $this->form()->closeTag($signupform); ?>


                                            </div>
                                        </div>
                                    </div>
                                    <!-- <div class="modal-footer">
                                        <button type="button" class="btn-u btn-u-default" data-dismiss="modal">Close</button>
                                        <button id="sign-up-button" type="button" class="btn-u btn-u-primary">SignUp</button>
                                    </div> -->
                                </div>
                            </div>
                        </div>
        </div>
    </div>
<div class="cities-list-line">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 md-margin-bottom-10">
                        <?php echo $this->navigation('Navigation_c')->menu()->setUlClass('cities-list-line-bar'); ?>
                    </div>
                </div>
            </div>    
        </div>
</div>

<div class="container content"> 


        <!-- Recent Works -->
        <div class="headline"><h2>Upcoming Events</h2></div>
<!--         <div class="heading heading-v1 margin-bottom-40">
                        <h2>Upcomming Events</h2>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged</p>
                    </div> -->
        <div class="row">
            <?php foreach ($eventsFirstLine as $event): ?>
            <div class="col-md-3 col-sm-6">
                <div class="thumbnails thumbnail-style thumbnail-kenburn">
                    <div class="index-thumbnail-img easy-block-v1">

                        <div class="index-event-date rgba-blue">
                            <!-- <span class="index-event-date-day"><?php //echo $event->getDateTimeEvent()->format('d'); ?></span> -->
                            <span class="index-event-date-month"><?php echo $event->getDateTimeEvent()->format('d'); ?> <?php echo $event->getDateTimeEvent()->format('F'); ?>, <?php echo $event->getDateTimeEvent()->format('l'); ?></span>
                            <!-- <span>Kyiv</span> -->
                        </div>

                        <div class="overflow-hidden">
                            <a href="<?php echo $this->url('fryday/event_details', array('country' => $event->getCity()->getCountry()->getName(), 'city' => $event->getCity()->getName(), 'dateslug' => $event->getDateSlug(), 'titleslug' => $event->getTitleSlug() )); ?>">
                                <img class="img-responsive" src="<?php echo '/uploads/events/' . $event->getId() . DIRECTORY_SEPARATOR . 'rect640x320_' . $event->getImage(); ?>" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="caption">
                        <a class="index-event-title  hover-effect fryday-w" href="<?php echo $this->url('fryday/event_details', array('country' => $event->getCity()->getCountry()->getName(), 'city' => $event->getCity()->getName(), 'dateslug' => $event->getDateSlug(), 'titleslug' => $event->getTitleSlug() )); ?>"> <?php echo $event->getTitle(); ?> <span><?php echo $event->getVenue()->getCity()->getName(); ?>, <?php echo $event->getVenue()->getName(); ?></span>
                        </a>  
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
        <div class="row">
            <?php foreach ($eventsSecondLine as $event): ?>
            <div class="col-md-3 col-sm-6">
                <div class="thumbnails thumbnail-style thumbnail-kenburn">
                    <div class="index-thumbnail-img easy-block-v1">
                        <div class="index-event-date rgba-blue">
                            <span class="index-event-date-month"><?php echo $event->getDateTimeEvent()->format('d'); ?> <?php echo $event->getDateTimeEvent()->format('F'); ?>, <?php echo $event->getDateTimeEvent()->format('l'); ?></span>
                            <!-- <span>Kyiv</span> -->
                        </div>

                        <div class="overflow-hidden">
                            <a href="<?php echo $this->url('fryday/event_details', array('country' => $event->getCity()->getCountry()->getName(), 'city' => $event->getCity()->getName(), 'dateslug' => $event->getDateSlug(), 'titleslug' => $event->getTitleSlug() )); ?>">
                                <img class="img-responsive" src="<?php echo '/uploads/events/' . $event->getId() . DIRECTORY_SEPARATOR . 'rect640x320_' . $event->getImage(); ?>" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="caption">
                        <p><a class="index-event-title  hover-effect fryday-w" href="<?php echo $this->url('fryday/event_details', array('country' => $event->getCity()->getCountry()->getName(), 'city' => $event->getCity()->getName(), 'dateslug' => $event->getDateSlug(), 'titleslug' => $event->getTitleSlug() )); ?>">
                            <?php echo $event->getTitle(); ?>
                            <span><?php echo $event->getVenue()->getCity()->getName(); ?>, <?php echo $event->getVenue()->getName(); ?></span>
                        </a> </p>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>

        <!-- Info Blokcs -->
        <div class="row margin-bottom-30">
            <!-- Welcome Block -->
            <div class="col-md-8 md-margin-bottom-40">
                <div class="headline"><h2>NEWS FROM FRYDAY</h2></div>
                <div class="magazine-news">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="magazine-news-img">
                                <a href="#"><img class="img-responsive" src="/frontend/img/995652_675939865837300_5120003958677719456_n.png" alt=""></a>
                            </div>
                            <h3><a href="#">Fryday is launching in San Jose, Costa Rica! Welcome to join!</a></h3>
                            <div class="by-author">
                                <strong>By Jack Villo</strong>
                                <span>/ September 19, 2013</span>
                            </div> 
                            <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate...</p>
                        </div>
                        <div class="col-md-4">
                            <div class="magazine-news-img">
                                <a href="#"><img class="img-responsive" src="/frontend/img/main/2.jpg" alt=""></a>
                            </div>
                            <h3><a href="#">Simelque Untine Culpaqui Officia Deserunt</a></h3>
                            <div class="by-author">
                                <strong>By Ann Diwver</strong>
                                <span>/ September 19, 2013</span>
                            </div> 
                            <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate...</p>
                        </div>
                        <div class="col-md-4">
                            <div class="magazine-news-img">
                                <a href="#"><img class="img-responsive" src="/frontend/img/main/3.jpg" alt=""></a>
                            </div>
                            <h3><a href="#">Simelque Untine Culpaqui Officia Deserunt</a></h3>
                            <div class="by-author">
                                <strong>By Admin</strong>
                                <span>/ September 19, 2013</span>
                            </div> 
                            <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate...</p>
                        </div>
                    </div>
                </div>
            </div><!--/col-md-8-->        

            <!-- Latest Shots -->
            <div class="col-md-4">
                <div class="headline"><h2>PARTNERS</h2></div>
                <div class="posts margin-bottom-40">
                    <dl class="dl-horizontal">
                        <dt><a href="#"><img src="/frontend/img/21216_537853716271950_34300625_n.png" alt=""></a></dt>
                        <dd>
                            <p><a href="#">Ferrari Store offers a wide range of clothing and accessories for adults and children from the legendary Ferrari brand!</a></p> 
                        </dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt><a href="#"><img src="/frontend/img/oriflame.jpg" alt=""></a></dt>
                        <dd>
                            <p><a href="#">Fryday's partner Oriflame is looking for talented co-workers to its Ukrainian head office.</a></p> 
                        </dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt><a href="#"><img src="/frontend/img/1000228_604435942910213_1273191221_n.jpg" alt=""></a></dt>
                        <dd>
                            <p><a href="#">With Custom Case you can order the cover for your phone that match your style and interests.</a></p> 
                        </dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt><a href="#"><img src="/frontend/img/547106_353190208057349_1589130915_n.jpg" alt=""></a></dt>
                        <dd>
                            <p><a href="#">Fryday is proud to announce that the Swedish company Volvo will be present at Fryday W with the Ambassador of Sweden on October 1st.</a></p> 
                        </dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt><a href="#"><img src="/frontend/img/995292.png" alt=""></a></dt>
                        <dd>
                            <p><a href="#">We are happy to present Beetroot Resources - our great friend and partner of the next Fryday W on Swedish business in Ukraine!</a></p> 
                        </dd>
                    </dl>
                </div>
            </div><!--/col-md-4-->
        </div>  
        <!-- End Info Blokcs -->

            <div id="clients-flexslider" class="flexslider home clients">
                <div class="headline"><h2>PHOTOS AND VIDEOS</h2></div>  
                <div class="row service-v1 margin-bottom-40">
                    <div class="col-md-3 md-margin-bottom-40">
                        <iframe width="100%" height="175px" src="//www.youtube.com/embed/NZyxjlPjG4M" frameborder="0" allowfullscreen></iframe>
                    </div>

                    <div class="col-md-3">
                        <iframe width="100%" height="175px" src="//www.youtube.com/embed/raT9Q-8AtLY" frameborder="0" allowfullscreen></iframe>
                    </div>
                    <div class="col-md-3 md-margin-bottom-40">
                        <iframe width="100%" height="175px" src="//www.youtube.com/embed/8gUNHReHcMM" frameborder="0" allowfullscreen></iframe>  
                          
                    </div>
                    <div class="col-md-3">
                        <iframe width="100%" height="175px" src="//www.youtube.com/embed/HEUBe_OoYFs" frameborder="0" allowfullscreen></iframe>  
                    </div>
                </div>  
            </div>

        <!-- Our Clients -->
        <div id="clients-flexslider" class="flexslider home clients">
            <div class="headline"><h2>FRYDAY'S PARTNERS</h2></div>
            <div class="row margin-bottom-40">
                <div class="col-md-12 md-margin-bottom-40">
                    <div id="owl-demo">
                    <?php foreach ($partners as $partner): ?>
                        <div class="item"><img src="<?php echo '/uploads/partners/' . $partner->getId() . DIRECTORY_SEPARATOR . 'carousel144x72_' . $partner->getLogo(); ?>" alt="Owl Image">
                        </div>
                    <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
</div>

<script>

    

    $(document).ready(function() 
    {
        $("#owl-demo").owlCarousel(
        {    
            autoPlay: 3000, //Set AutoPlay to 3 seconds
             
            items : 6,
            itemsDesktop : [1199,3],
            itemsDesktopSmall : [979,3]
         
        });
    });



    $( "form" ).submit(function( event ) {
        if ( $( "input:first" ).val() === "correct" ) {
            $( "span" ).text( "Validated..." ).show();
            return;
        }
        $( "span" ).text( "Not valid!" ).show().fadeOut( 1000 );
        event.preventDefault();
    });

    $(document).ready(function() {
        $("#sign-up-button").click(function(){
            // alert("button");
            $.post("/sign-up", { email: $("#signup-email").val(), }, function(data){

                // console.log(data.message);
                console.log(data.error_message);
                console.log(data.success);

                if(data.success)
                {
                    // $( "#email-errors" ).empty();
                    $( "#emailinput" ).empty();
                    $( "#emailinput" ).append('<div class="note note-error">Please check your email for a message from Fryday to confirm your subscription</div>');
                    // $("#myModalLabel").replaceWith("");
                }
                else
                {
                    $( "#email-errors" ).empty();

                    for (var key in data.error_message) 
                    {
                       var obj = data.error_message[key];
                       for (var prop in obj) 
                       {
                            // important check that this is objects own property 
                            // not from prototype prop inherited
                            
                            if(obj.hasOwnProperty(prop))
                            {
                                if(prop == 'objectFound')
                                {
                                    console.log(prop);
                                    $( "#email-errors" ).append('<div class="note note-error">' + obj[prop] + '. Please use your password.</div>');
                                }
                                else
                                {
                                    $( "#email-errors" ).append('<div class="note note-error">' + obj[prop] + '</div>');
                                }
                            }
                        }
                    }
                }
                



            }, 'json');
        }); 
    });
</script>