<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Speaker</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Speaker</li>
        </ul>
    </div>
</div>

<div class="container content">		
    	<div class="row margin-bottom-40">
        	<div class="col-md-6 md-margin-bottom-40">
                <p>Fryday is an international network of cosmopolitan professionals present in 30 cities in 20+ countries and has 150k+ registered members.  Fryday offers unique networking opportunities in a truly international environment.</p>
                <p>Speakers enjoy speaking at Fryday W events as they can meet an interesting and senior audience. Speakers might be interested in promoting themselves, their company or it might be part of their job to communicate a certain message.</p><p>Members appreciate the free format of Fryday’s events and enjoy participating at a time of their choosing and the opportunity to bring guests.</p>
                <p>Fryday offers speakers:</p>
                <ul class="list-unstyled">
                    <li><i class="fa fa-check color-green"></i> Senior crowd</li>
                    <li><i class="fa fa-check color-green"></i> Large number of guests</li>
                    <li><i class="fa fa-check color-green"></i> Professional and extensive online promotion</li>
                    <li><i class="fa fa-check color-green"></i> Media presence at the event</li>
                </ul>
            </div>

        	<div class="col-md-6 md-margin-bottom-40">
                <div class="responsive-video">
                	<iframe src="//www.youtube.com/embed/YT7UYJJdUQY" frameborder="0" allowfullscreen></iframe>
                   	<!--  <iframe src="http://player.vimeo.com/video/9679622" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" frameborder="0"></iframe>  -->
                </div>
            </div>
        </div><!--/row-->

    	
    </div>