<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left"><?php echo $event->getTitle(); ?></h1>
        <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Event</li>
        </ul>
    </div>
</div>


<div class="content container">
            <div class="page-wrapper">
                <div class="page-content">
                    <div class="row page-row">
                        <div class="jobs-wrapper col-md-8 col-sm-7">           
                            <h3 class="title"></h3>
                            <div class="event-main-img">
                                <img class="img-responsive" src="<?php echo '/uploads/events/' . $event->getId() . DIRECTORY_SEPARATOR . 'rect640x320_' . $event->getImage(); ?>" alt="<?php echo $event->getTitle(); ?>">
                            </div>
                           <!--  <div class="fb-like" data-href="https://fryday.net/event/<?php $event->getVenue()->getId(); ?>" data-layout="standard" data-action="like" data-show-faces="true" data-share="true">
                            </div> -->
                            <div class="fb-like" data-href="http://fryday.net/<?php echo $event->getVenue()->getCity()->getRoute() . '/event/' . $event->getDateSlug() . '/' . $event->getTitleSlug(); ?>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>

                            <br><br>
                            <div class="box box-border page-row">
                                <blockquote class="hero-unify">
                                    <ul class="list-unstyled">
                                        <li><strong>Date:</strong> <?php echo $event->getDateTimeEvent()->format('l, F jS'); ?> </li>
                                        <li><strong>Time:</strong> <?php echo $event->getDateTimeEvent()->format('H:i'); ?></li>
                                        <li><strong>Venue:</strong> <?php echo $event->getVenue()->getName(); ?></li>
                                        <li><strong>Address:</strong> <?php echo $event->getVenue()->getAddress(); ?></li>
                                        <li><strong>Entrance fee:</strong> <?php echo $event->getEntranceFee() . " " . $event->getCurrency()->getCode(); ?></li>
                                    </ul>  
                                </blockquote>
                              
                            </div>
                            <p>
                            <?php echo nl2br($event->getDetails()); ?>
                            </p>
                                                                                        
                        </div><!--//jobs-wrapper-->
                        <aside class="page-sidebar  col-md-3 col-md-offset-1 col-sm-4 col-sm-offset-1">                    
                            <section class="widget has-divider">
                                <h3 class="title">Video tour</h3>
                                <iframe class="iframe" src="//www.youtube.com/embed/Ks-_Mh1QhMc?rel=0&amp;wmode=transparent" allowfullscreen="" =""="" frameborder="0"></iframe>
                            </section><!--//widget-->

                        </aside>
                    </div><!--//page-row-->
                </div><!--//page-content-->
            </div><!--//page--> 
        </div>

