<div class="profile container content">
    	<div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <img class="img-responsive profile-img margin-bottom-20" src="<?php echo '/uploads/users' . DIRECTORY_SEPARATOR . $this->identity()->getId() . DIRECTORY_SEPARATOR . 'square264x264_' . $this->identity()->getImage(); ?>" alt="">
                <?php echo $this->navigation('admin_navigation')->menu()->setUlClass('list-group sidebar-nav-v1 margin-bottom-40')->setAddClassToListItem(true)->escapeLabels(false); ?>
                <hr>
            </div>
            <!--End Left Sidebar-->
            
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <!--Table Search v2-->
                    <?php $form->setAttribute('action', $this->url('administrator/default', array('controller' => 'event', 'action' => 'create-first-step')))->prepare(); ?>
                    <?php echo $this->form()->openTag($form); ?>
                    <!-- <form action="" class="sky-form"> -->
                    <header>New Event</header>
                    
                    <fieldset>
                        <section class="col-md-12">
                            <?php echo $this->formLabel($this->form->get('title')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('title')); ?>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('title')); ?>
                        </section>

                        <section class="col-md-6">
                            <?php echo $this->formLabel($this->form->get('date')); ?>
                            <label class="input">
                                <i class="icon-append fa fa-calendar"></i>
                                <?php echo $this->formInput($this->form->get('date')); ?>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('date')); ?>
                        </section>

                        <section class="col-md-6">
                            <?php echo $this->formLabel($this->form->get('time')); ?>
                            <label class="input">
                                <i class="icon-append fa fa-clock-o"></i>
                                <?php echo $this->formInput($this->form->get('time')); ?>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('time')); ?>
                        </section>
                        <!-- <section>
                            <?php //echo $this->formLabel($this->form->get('email')); ?>
                            <label class="input">
                                <?php //echo $this->formInput($this->form->get('email')); ?>
                            </label>
                        </section> -->

<!--                         <section>
                            <?php //echo $this->formLabel($this->form->get('lastName')); ?>
                            <label class="input">
                                <?php //echo $this->formInput($this->form->get('lastName')); ?>
                            </label>
                        </section> -->
                        
<!--                         <section>
                            <?php //echo $this->formLabel($this->form->get('profileImage')); ?>
                            <label for="file" class="input input-file">
                                <div class="button">
                                    <?php //echo $this->formFile($this->form->get('profileImage')); ?>
                                    Browse
                                </div>
                                <input readonly="" type="text">
                                <?php //echo $this->formFile($this->form->get('profileImage')); ?>
                            </label>
                        </section> -->

<!--                         <section>
                            <?php //echo $this->formLabel($this->form->get('username')); ?>
                            <label class="input">
                                <?php //echo $this->formInput($this->form->get('username')); ?>
                            </label>
                        </section> -->

<!--                         <section>
                            <?php //echo $this->formLabel($this->form->get('password')); ?>
                            <label class="input">
                                <?php //echo $this->formInput($this->form->get('password')); ?>
                            </label>
                        </section> -->               
                            
<!--                         <section>
                            <?php //echo $this->formLabel($this->form->get('role')); ?>
                            <label class="select">
                                <?php //echo $this->formSelect($this->form->get('role')); ?>
                                <i></i>
                            </label>
                        </section> -->

                        <!-- <section>
                            <?php //echo $this->formLabel($this->form->get('city')); ?>
                            <label class="select">
                                <?php //echo $this->formSelect($this->form->get('city')); ?>
                                <i></i>
                            </label>
                        </section> -->

                    </fieldset>
                    
                    <footer>
                        <button type="submit" class="btn-u">Next</button>
                        <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">Back</button>
                    </footer>
                <!-- </form> -->
                    <?php echo $this->form()->closeTag($form); ?>
                    <!--End Table Search v2-->
                </div>
                <!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div>

<script>
    // $(function() {
    //     $( "#datepicker" ).datepicker({
    //         prevText: '<i class="fa fa-angle-left"></i>',
    //         nextText: '<i class="fa fa-angle-right"></i>'
    //     });
    // });
    $('#event-date').datepicker({
        prevText: '<i class="fa fa-angle-left"></i>',
        nextText: '<i class="fa fa-angle-right"></i>',
    });
    $('#event-time').datetimepicker({
        format:'H:i',
        datepicker:false,
    });
</script>