            
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <!--Table Search v2-->
                    <?php $form->setAttribute('action', $this->url('administrator/default', array('controller' => 'event', 'action' => 'edit', 'id' => $event->getId())))->prepare(); ?>
                    <?php echo $this->form()->openTag($form); ?>
                    <!-- <form action="" class="sky-form"> -->
                    <header><?php echo $event->getTitle(); ?></header>
                    

                    <fieldset>
                        <section class="col-md-12">
                            <?php echo $this->formLabel($this->form->get('title')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('title')); ?>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('title')); ?>
                        </section>

                            <?php if($event->getImage() != null): ?>
                            <div class="col col-12 imag_center">
                                <img style="max-height: 320px;max-width: 640px; "id="imagepreview" src="<?php echo '/uploads/events' . DIRECTORY_SEPARATOR . $event->getId() . DIRECTORY_SEPARATOR . $event->getImage(); ?>" alt="your image" />
                            </div>
                            <?php else: ?>
                            <div class="col col-12 imag_center">
                                <img style="max-height: 320px;max-width: 640px; "id="imagepreview" src="/frontend/img/noimage.png" alt="your image" />
                            </div>
                            <?php endif; ?>

                            <section class="col col-6">
                                <?php echo $this->formLabel($this->form->get('image')); ?>
                                <label for="file" class="input input-file">
                                    <div class="button">
                                        <?php echo $this->formFile($this->form->get('image')); ?>
                                        Browse
                                    </div>
                                    <input readonly="" type="text">
                                    <?php //echo $this->formFile($this->form->get('profileImage')); ?>
                                </label>
                                <?php echo $this->formInput($this->form->get('xStartCrop')); ?>
                                <?php echo $this->formInput($this->form->get('yStartCrop')); ?>
                                <?php echo $this->formInput($this->form->get('widthCrop')); ?>
                                <?php echo $this->formInput($this->form->get('heightCrop')); ?>
                                <?php echo $this->formInput($this->form->get('widthCurrent')); ?>
                                <?php echo $this->formInput($this->form->get('heightCurrent')); ?>
                            </section>


                        <section class="col col-6">
                            <?php echo $this->formLabel($this->form->get('venue')); ?>
                            <label class="select">
                                <?php echo $this->formSelect($this->form->get('venue')); ?>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('venue')); ?>
                        </section>

                        <section class="col-md-6">
                            <?php echo $this->formLabel($this->form->get('date')); ?>
                            <label class="input">
                                <i class="icon-append fa fa-calendar"></i>
                                <?php echo $this->formInput($this->form->get('date')); ?>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('date')); ?>
                        </section>

                        <section class="col-md-6">
                            <?php echo $this->formLabel($this->form->get('time')); ?>
                            <label class="input">
                                <i class="icon-append fa fa-clock-o"></i>
                                <?php echo $this->formInput($this->form->get('time')); ?>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('time')); ?>
                        </section>
                        
                        <section class="col-md-6">
                            <?php echo $this->formLabel($this->form->get('entrancefee')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('entrancefee')); ?>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('entrancefee')); ?>
                        </section>

                        <section class="col-md-6">
                            <?php echo $this->formLabel($this->form->get('currency')); ?>
                            <label class="select">
                                <?php echo $this->formSelect($this->form->get('currency')); ?>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('currency')); ?>
                        </section>

                        <section class="col-md-12">
                            <!-- <label class="label">Textarea</label> -->
                            <?php echo $this->formLabel($this->form->get('details')); ?>
                            <label class="textarea">
                                <?php echo $this->formTextarea($this->form->get('details')); ?>
                            </label>
                        </section>

                    </fieldset>

                    <footer>
                        <button type="submit" class="btn-u">Save</button>
                        <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">Back</button>
                    </footer>
                <!-- </form> -->
                    <?php echo $this->form()->closeTag($form); ?>
                    <!--End Table Search v2-->
                </div>
                <!--End Profile Body-->
            </div>

<script>
    $('#event-date').datepicker({
        prevText: '<i class="fa fa-angle-left"></i>',
        nextText: '<i class="fa fa-angle-right"></i>',
    });
    $('#event-time').datetimepicker({
        format:'H:i',
        datepicker:false,
        step:15,
    });

    function readURL(input) {

    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#imagepreview').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
        }
    }

    $(document).ready(function () {
        $('#imagepreview').imgAreaSelect({ 
            // maxWidth: 200, 
            // maxHeight: 150, 
            aspectRatio: '2:1',
            handles: true,
            // show: true,
            onSelectChange: preview,
            x1: parseInt($('#x-start-crop').val(), 10),
            y1: parseInt($('#y-start-crop').val(), 10),
            x2: parseInt($('#x-start-crop').val(), 10) + parseInt($('#width-crop').val(), 10),
            y2: parseInt($('#y-start-crop').val(), 10) + parseInt($('#height-crop').val(), 10),
        });
    });

    $("#image").change(function(){
        readURL(this);
    });

    function preview(img, selection) {
        $('#width-current').val(img.clientWidth);  
        $('#height-current').val(img.clientHeight); 
        $('#x-start-crop').val(selection.x1);  
        $('#y-start-crop').val(selection.y1);
        $('#width-crop').val(selection.width);  
        $('#height-crop').val(selection.height); 
    } 

</script>
