<div class="profile container content">
    	<div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <?php if($this->identity()->getImage() != null): ?>
                <img class="img-responsive profile-img margin-bottom-20" src="<?php echo '/uploads/users' . DIRECTORY_SEPARATOR . $this->identity()->getId() . DIRECTORY_SEPARATOR . 'square264x264_' . $this->identity()->getImage(); ?>" alt="<?php echo $user->getFirstName() . " " . $user->getLastName(); ?>">
                <?php else: ?>
                <img class="img-responsive md-margin-bottom-10" src="/frontend/img/noavatar.png" alt="<?php echo $this->identity()->getFirstName() . " " . $this->identity()->getLastName(); ?>">
                <?php endif; ?>
                <?php echo $this->navigation('admin_navigation')->menu()->setUlClass('list-group sidebar-nav-v1 margin-bottom-40')->setAddClassToListItem(true)->escapeLabels(false); ?>
                <hr>
            </div>
            <!--End Left Sidebar-->
            
            <div class="col-md-9">
                <!--Profile Body-->
                
                 
                    <div class="profile-body">
                        <div class="row">
                            <div class="col-md-12">

                                <?php if(count($flashMessages)) : ?>
                                <div class="alert alert-success fade in">
                                    <?php foreach ($flashMessages as $msg) : ?>
                                    <?php echo $msg; ?> <br>
                                    <?php endforeach; ?>
                                </div>
                                <?php endif; ?>

                                <?php if(!$event->getNewsletterCreated()): ?>
                                <div class="alert alert-warning fade in">
                                    <h4>Newsletter has not been created, you can not sending mails to inform subcribers about this event</h4>
                                    <p>
                                        <!-- <a class="btn-u btn-u-xs btn-u-red" href="#">Take this action</a> --> <a class="btn-u btn-u-xs btn-u-sea" href="<?php echo $this->url('administrator_content/default', array('controller' => 'newsletter', 'action' => 'create', 'id' => $event->getId())); ?>">Create newsletter</a>
                                    </p>
                                </div>
                                <?php else: ?>
                                <div class="alert alert-warning fade in">
                                    <h4>Newsletter about this event has not been sent to subscribers</h4>
                                    <p>
                                        <a class="btn-u btn-u-xs btn-u-sea" href="<?php echo $this->url('administrator_content/default', array('controller' => 'newsletter', 'action' => 'send', 'id' => $event->getNewsletter()->getId())); ?>">Send</a>
                                        <a class="btn-u btn-u-xs btn-u-dark-blue" href="<?php echo $this->url('administrator_content/default', array('controller' => 'newsletter', 'action' => 'view', 'id' => $event->getNewsletter()->getId())); ?>" target="_blank">Preview</a>
                                        <a class="btn-u btn-u-xs btn-u-orange" href="<?php echo $this->url('administrator_content/default', array('controller' => 'newsletter', 'action' => 'view', 'id' => $event->getNewsletter()->getId())); ?>" target="_blank">Edit</a>
                                        <a class="btn-u btn-u-xs btn-u-red" href="<?php echo $this->url('administrator_content/default', array('controller' => 'newsletter', 'action' => 'view', 'id' => $event->getNewsletter()->getId())); ?>" target="_blank">Delete</a>
                                    </p>
                                </div> 
                                <?php endif; ?>
                            </div>
                        </div>
                        <a href="<?php echo $this->url('administrator_content/default', array('controller' => 'event', 'action' => 'edit', 'id' => $event->getId())); ?>" class="btn-u btn-brd btn-brd-hover btn-u-dark btn-u-xs margin-bottom-20"><i class="fa fa-pencil"></i> Edit</a>
                        <?php if($event->getPublished()): ?>
                        <a href="<?php echo $this->url('administrator_content/default', array('controller' => 'event', 'action' => 'unpublish', 'id' => $event->getId())); ?>" class="btn-u btn-brd btn-brd-hover btn-u-dark btn-u-xs margin-bottom-20"><i class="fa fa-times"></i> Unpublish</a>
                        <?php else: ?>
                        <a href="<?php echo $this->url('administrator_content/default', array('controller' => 'event', 'action' => 'publish', 'id' => $event->getId())); ?>" class="btn-u btn-brd btn-brd-hover btn-u-dark btn-u-xs margin-bottom-20"><i class="fa fa-share"></i> Publish</a>
                        <?php endif; ?>
                        <a href="#" class="btn-u btn-brd btn-brd-hover btn-u-dark btn-u-xs margin-bottom-20"><i class="fa fa-facebook"></i> Create Event On Facebook</a>
                        <a href="<?php echo $this->url('administrator_content/default', array('controller' => 'event', 'action' => 'create-first-step' )); ?>" class="btn-u btn-brd btn-brd-hover btn-u-dark btn-u-xs margin-bottom-20"><i class="fa fa-trash-o"></i> Delete Event</a>
                        <!-- <div class="alert alert-success fade in margin-bottom-40">
                            <h4>Event Published!</h4>
                            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.
                        </div> -->

                        <!-- <div class="alert alert-danger fade in"> -->
                            <!-- <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button> -->
                            <!-- <h4>Newsletter didn't send!</h4>
                            <p>Change this and that and try again. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum.</p>
                            <p>
                                <a class="btn-u btn-u-red" href="#">Send Mails To Subscribers</a> 
                                <a class="btn-u btn-u-sea" href="#">Create Template</a>
                            </p>
                        </div> -->

                        <div class="profile-bio">
                            <div class="col-md-12">
                                <h2><?php echo $event->getTitle(); ?></h2>
                            </div>
                                <div class="row">
                                <div class="col-md-12">
                                    <div class="event-main-img">
                                    <img class="img-responsive" src="<?php echo '/uploads/events' . DIRECTORY_SEPARATOR . $event->getId() . DIRECTORY_SEPARATOR . 'rect640x320_' .$event->getImage(); ?>" alt="<?php //echo $event->getTitle(); ?>">
                                    <!-- <img class="img-responsive" src="/img/logo.png" alt="<?php //echo $event->getTitle(); ?>"> -->
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    
                                    <span><strong>Date:</strong> <?php echo $event->getDateTimeEvent()->format('l, F jS'); ?></span>
                                    <span><strong>Time:</strong> <?php echo $event->getDateTimeEvent()->format('H:i'); ?></span>
                                    <span><strong>Venue:</strong> <?php echo $event->getVenue()->getName(); ?></span>
                                    <?php if($event->getCurrency() === null): ?>
                                        <span><strong>Entrance fee:</strong> Free</span>
                                    <?php else: ?>
                                        <span><strong>Entrance fee:</strong> <?php echo $event->getEntranceFee() . " " . $event->getCurrency()->getCode(); ?></span>
                                    <?php endif; ?>
                                    <hr>
                                    <p><?php echo nl2br($event->getDetails()); ?></p>
                                </div>
                            </div>    
                        
                            <footer>

                    </footer>
                <!-- </form> -->
                    
                </div><!--/end row-->

                </div>
                <!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div>