<ul class ="nav main-menu" >
	<?php 
	foreach ($this->container as $page): 
		?>
		<?php 
		if($page->hasPages()): 
			?>
			<!-- Set parent page as active if child is active  -->
			<?php 
			foreach($page->getPages() as $child): 
				?>
				<?php 
				if($child->isActive() || $page->isActive()): 
					?>
					<?php 
					$active = 1; 
					?>
				<?php 
				endif; 
				?>
			<?php 
			endforeach; 
			?>

			<!-- Rendering pages with children  -->
			<li class=<?php echo $active ? '"gropdown active"' : '"gropdown"' ?> >
				<?php echo $this->navigation('secondary_navigation')->menu()->htmlify($page); ?>
				<?php 
				if($active): 
					?>
					<ul class="dropdown-menu" style="display: block;" > 
						<?php 
						foreach($page->getPages() as $child): 
							?>
							<?php 
							if($child->isVisible()) :
								?>
								<li>
									<?php 
									echo $this->navigation('secondary_navigation')->menu()->htmlify($child);
									?>
								</li>
							<?php
							endif; 
							?>
			            <?php 
			            endforeach; 
			            ?>
					</ul>
				<?php
				endif; 
				?>
			</li>
		<?php 
		else: 
			?>
			<!-- Rendering pages without children  -->
			<li class=<?php echo $page->isActive() ? 'active' : '' ?> >
				<?php 
					echo $this->navigation('secondary_navigation')->menu()->htmlify($page); 
				?>
			</li>
		<?php 
		endif; 
		?>
	<?php 
	endforeach; 
	?>
</ul>