<div class="row">
	<div class="col-lg-12">
		<div class="page-header col-lg-7 col-lg-offset-2">
		  	<h2>Creating a Venue <!-- <small>Subtext for header</small> --></h2>
		</div>
		<?php $form->setAttribute('action', $this->url('backend/default', array('controller' => 'venue', 'action' => 'create')))->prepare(); ?>
		<?php echo $this->form()->openTag($form); ?>
		<div class="col-lg-7 col-lg-offset-2">

			<div class="row">
	            <?php echo $this->formLabel($this->form->get('name')); ?>
	            <div class="input-group input-group-sm col-lg-6">
	                <?php echo $this->formInput($this->form->get('name')); ?>
	                <?php echo $this->FormElementErrors($this->form->get('name')); ?>
	            </div>
            </div>
            			
			<div class="row">
	            <?php echo $this->formLabel($this->form->get('profileImage')); ?>
	            <div class="input-group input-group-sm col-lg-6">
		            <?php echo $this->formFile($this->form->get('profileImage')); ?>
		            <?php echo $this->FormElementErrors($this->form->get('profileImage')); ?>
	            </div>
	        </div>

            <div class="row">
	            <?php echo $this->formLabel($this->form->get('category')); ?>
	            <div class="input-group input-group-sm col-lg-6">
	                <?php echo $this->formSelect($this->form->get('category')); ?>
	                <?php echo $this->FormElementErrors($this->form->get('category')); ?>
	            </div> 
        	</div>

        	<div class="row">
	            <?php echo $this->formLabel($this->form->get('city')); ?>
	            <div class="input-group input-group-sm col-lg-6">
	                <?php echo $this->formSelect($this->form->get('city')); ?>
	                <?php echo $this->FormElementErrors($this->form->get('city')); ?>
	            </div> 
        	</div>

        	<div class="row">
	            <?php echo $this->formLabel($this->form->get('phone')); ?>
	            <div class="input-group input-group-sm col-lg-6">
	                <?php echo $this->formInput($this->form->get('phone')); ?>
	                <?php echo $this->FormElementErrors($this->form->get('phone')); ?>
	            </div>
	        </div>

	        <div class="row">
	            <?php echo $this->formLabel($this->form->get('website')); ?>
	            <div class="input-group input-group-sm col-lg-6">
	                <?php echo $this->formInput($this->form->get('website')); ?>
	                <?php echo $this->FormElementErrors($this->form->get('website')); ?>
	            </div>
	        </div>

	        <div class="row">
	            <?php echo $this->formLabel($this->form->get('email')); ?>
	            <div class="input-group input-group-sm col-lg-6">
		            <?php echo $this->formInput($this->form->get('email')); ?>
		            <?php echo $this->FormElementErrors($this->form->get('email')); ?>
	            </div>
	        </div>

	        <div class="row">
	            <?php echo $this->formLabel($this->form->get('address')); ?>
	            <div class="input-group input-group-sm col-lg-6">
		            <?php echo $this->formInput($this->form->get('address')); ?>
		            <?php echo $this->FormElementErrors($this->form->get('address')); ?>
	            </div>
	        </div>

	        <div class="row">
	            <div class="input-group input-group-sm col-lg-6 col-lg-offset-4">
		            <?php echo $this->formSubmit($this->form->get('submit')); ?>
	            </div>
	        </div>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
	</div>
</div>