<div class="row">
	<div class="col-lg-10 col-lg-offset-1">
		<h4><a href="<?php echo $this->url('backend/default', array('controller' => 'venue', 'action' => 'create')); ?>"><i class="fa fa-plus fa-fw"></i> NEW</a></h4>
		<br>
	</div>
</div>

<?php foreach ($venues as $venue): ?>
	<div class="row">
		<div class="col-lg-2 col-lg-offset-1">
			<?php 
			$imageBase64 = null; 
			$imageName = $venue->getProfileImage();
			if (file_exists($imageName)) {
				$handle = fopen($imageName, "r");
				$imageBase64 = fread($handle, filesize($imageName));
				fclose($handle);
			}
			?>
			<img src="data:image/png;base64,<?php echo base64_encode($imageBase64) ?>" class="img-rounded" height="128" width="128">
		</div>
		<div class="col-lg-7">
			<h4 class="text-left"><?php echo $venue->getName(); ?></h4>
			<p class="venue-preview-category"><?php echo $venue->getCategory()->getName(); ?></p><br>
			<i class="fa fa-map-marker fa-fw"></i><?php echo $venue->getCity()->getName(); ?>, <?php echo $venue->getCity()->getCountry()->getName(); ?> 
		</div>
	</div>
	<hr class="col-lg-9 col-lg-offset-1">
<?php endforeach; ?>