<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/theme.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
        
                        // ->prependStylesheet($this->basePath() . '/css/style.css')
                        // ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        // ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>

    <div class="header">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="logo"><a href="index.html"><img src="/img/logo.png" alt=""></a></div>                 
                </div>
                <div class="col-md-6">
                    <div class="top_block">
                        <p>Call Us Now:  +1 ( 777) 637-27-97</p>
                        <div class="follow_us">
                            <ul>
                                <li><a data-original-title="" href="#" class="facebook">Facebook</a></li>
                                <li><a data-original-title="" href="#" class="twitter">Twitter</a></li>
                            </ul>
                        </div>
                    </div>                           
                </div>
            </div>                
        </div>
        
        <div class="container">
            <div id="menu_block">
                <div class="row">
                    <div class="col-md-12">
                        <div class="navbar navbar_ clearfix">
                            <nav id="main_menu">
                                <div class="menu_wrap">
                                    <ul class="nav sf-menu sf-js-enabled">
                                        <li class="current"><a href="index.html">Home</a></li>
                                        <li><a href="#">Events</a></li>
                                        <li><a href="#">Advertise</a></li>
                                        <li><a href="#">Partner</a></li>
                                        <li><a href="#">Media</a></li>
                                        <li><a href="#">Member</a></li>
                                        <li><a href="#">Franchise</a></li>
                                        <li><a href="#">About</a></li>
                                        <li><a href="#">Contact</a></li>
                                    </ul>
                                </div>   
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br><br>
        <div class="container">
            <div class="row">

                <div class="col-md-4">
                    <div class="post">
                        <h3 class="title">
                            <span>
                                <a href="blog_post.html">Fryday Kyiv W with Igor Gut</a>
                            </span>
                        </h3>
                        <div style="position: relative; display: block;" class="gsWrapper"><img src="/img/photo_001.jpg" class="greyScale" alt="">
                            <canvas class="gsCanvas" height="100" width="300" style="left: 0px; position: absolute; top: 0px; opacity: 0.3249;">
                            </canvas>
                        </div>
                    </div>
                </div>
                <div class="col-md-1"></div>
                <div class="col-md-4">iuyu</div>
                <div class="col-md-3">
                    <h3 class="title">
                        <span>
                            <a href="blog_post.html">Featured Topics</a>
                        </span>
                    </h3>
                </div>
            </div>
        </div>
    </div>
   <!-- <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php //echo $this->url('home') ?>"><img src="<?php //echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php //echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php //echo $this->url('home') ?>"><?php //echo $this->translate('Home') ?></a></li>
                    </ul>
                </div>--><!--/.nav-collapse -->
            <!-- </div>
        </nav>
        <div class="container">
            <?php //cho $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php //echo date('Y') ?> by Zend Technologies Ltd. <?php //echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>--><!-- /container -->
        <!--<?php //echo $this->inlineScript() ?>
    </body> -->
    </body>
</html>
