<div class="profile container content">
        <div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <img class="img-responsive profile-img margin-bottom-20" src="<?php echo '/uploads/users' . DIRECTORY_SEPARATOR . $this->identity()->getId() . DIRECTORY_SEPARATOR . 'square264x264_' . $this->identity()->getImage(); ?>" alt="">
                <?php echo $this->navigation('admin_navigation')->menu()->setUlClass('list-group sidebar-nav-v1 margin-bottom-40')->setAddClassToListItem(true)->escapeLabels(false); ?>
                <hr>
            </div>
            <!--End Left Sidebar-->
            
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <!--Table Search v2-->
                    <?php $form->setAttribute('action', $this->url('administrator_content/default', array('controller' => 'city', 'action' => 'create-second-step', 'id' => $cityID) ))->prepare(); ?>
                    <?php echo $this->form()->openTag($form); ?>
                    <!-- <form action="" class="sky-form"> -->
                    <header>Add City</header>

                    <!-- <form method="POST">
                         <div id="dynamicInput">
                              Entry 1<br><input type="text" name="myInputs[]">
                         </div>
                         
                    </form> -->
                                        
                    <fieldset id="fieldset_test">
                        <div class="col col-12 imag_center">
                            <img style="max-height: 320px;max-width: 640px; "id="imagepreview" src="/frontend/img/noimage.png" alt="your image" />
                        </div>

                            <section class="col col-6">
                                <?php echo $this->formLabel($this->form->get('image')); ?>
                                <label for="file" class="input input-file">
                                    <div class="button">
                                        <?php echo $this->formFile($this->form->get('image')); ?>
                                        Browse
                                    </div>
                                    <input readonly="" type="text">
                                    <?php //echo $this->formFile($this->form->get('profileImage')); ?>
                                </label>
                                <?php echo $this->formInput($this->form->get('x')); ?>
                                <?php echo $this->formInput($this->form->get('y')); ?>
                                <?php echo $this->formInput($this->form->get('w')); ?>
                                <?php echo $this->formInput($this->form->get('h')); ?>
                                <?php echo $this->formInput($this->form->get('cw')); ?>
                                <?php echo $this->formInput($this->form->get('ch')); ?>
                            </section>

                        <section class="col-md-6">
                            <!-- <label class="label">Select</label> -->
                            <?php echo $this->formLabel($this->form->get('user')); ?>
                            <label class="select">
                                <?php echo $this->formSelect($this->form->get('user')); ?>
                                <i></i>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('user')); ?>
                        </section>

                        <!-- <input type="button" value="Add another text input" onClick="addInput('fieldset_test');"> -->
                        <!-- <section class="col-md-6">
                            <?php //echo $this->formLabel($this->form->get('name')); ?>
                            <label class="input">
                                <?php //echo $this->formInput($this->form->get('name')); ?>
                            </label>
                            <?php //echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('name')); ?>
                        </section> -->

                    </fieldset>
                    
                    <footer>
                        <button type="submit" class="btn-u">Save</button>
                        <!-- <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">Back</button> -->
                    </footer>
                <!-- </form> -->
                    <?php echo $this->form()->closeTag($form); ?>
                    <!--End Table Search v2-->
                </div>
                <!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div>

    <script>
        function readURL(input) {

    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#imagepreview').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
        }
    }

    $(document).ready(function () {
        $('#imagepreview').imgAreaSelect({ 
            // maxWidth: 200, 
            // maxHeight: 150, 
            aspectRatio: '2:1',
            handles: true,
            // show: true,
            onSelectChange: preview,
        });
    });

    $("#city-image").change(function(){
        readURL(this);
    });

    function preview(img, selection) {  
        $('#city-cw').val(img.clientWidth);  
        $('#city-ch').val(img.clientHeight);  
        $('#city-x').val(selection.x1);  
        $('#city-y').val(selection.y1); 
        $('#city-w').val(selection.width);  
        $('#city-h').val(selection.height);
    }
        // var counter = 1;
        // var limit = 3;
        // function addInput(divName){
        //      // if (counter == limit)  {
        //      //      alert("You have reached the limit of adding " + counter + " inputs");
        //      // }
        //      // else {
        //           var newdiv = document.createElement('section');
        //           newdiv.innerHTML = "Entry " + (counter + 1) + " <br><input type='text' name='myInputs[]'>";
        //           document.getElementById(divName).appendChild(newdiv);
        //           counter++;
        //      // }
        // }
    </script>