<div class="profile container content">
        <div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <img class="img-responsive profile-img margin-bottom-20" src="<?php echo $this->identity()->getProfileImage(); ?>" alt="">
                <?php echo $this->navigation('admin_navigation')->menu()->setUlClass('list-group sidebar-nav-v1 margin-bottom-40')->setAddClassToListItem(true)->escapeLabels(false); ?>
                <hr>
            </div>
            <!--End Left Sidebar-->
            
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <!--Table Search v2-->
                    <?php $form->setAttribute('action', $this->url('administrator_content/default', array('controller' => 'city', 'action' => 'create-first-step')))->prepare(); ?>
                    <?php echo $this->form()->openTag($form); ?>
                    <!-- <form action="" class="sky-form"> -->
                    <header>Create New City</header>
                    
                    <fieldset>

                        <!-- <section>
                            <?php //echo $this->formLabel($this->form->get('profileImage')); ?>
                            <label for="file" class="input input-file">
                                <div class="button">
                                    <?php //echo $this->formFile($this->form->get('profileImage')); ?>
                                    Browse
                                </div>
                                <input readonly="" type="text">
                                <?php //echo $this->formFile($this->form->get('profileImage')); ?>
                            </label>
                        </section>   -->            
                            
                        <section class="col-md-6">
                            <!-- <label class="label">Select</label> -->
                            <?php echo $this->formLabel($this->form->get('country')); ?>
                            <label class="select">
                                <?php echo $this->formSelect($this->form->get('country')); ?>
                                <i></i>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('country')); ?>
                        </section>

                        <section class="col-md-6">
                            <?php echo $this->formLabel($this->form->get('name')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('name')); ?>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('name')); ?>
                        </section>

                    </fieldset>
                    
                    <footer>
                        <button type="submit" class="btn-u">Next</button>
                        <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">Back</button>
                    </footer>
                <!-- </form> -->
                    <?php echo $this->form()->closeTag($form); ?>
                    <!--End Table Search v2-->
                </div>
                <!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div>