            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <!--Table Search v2-->
                    <?php $form->setAttribute('action', $this->url('administrator/default', array('controller' => 'city', 'action' => 'create-first-step')))->prepare(); ?>
                    <?php echo $this->form()->openTag($form); ?>
                    <!-- <form action="" class="sky-form"> -->
                    <header>Add City</header>
                    
                    <fieldset>                        
                        <section class="col-md-6">
                            <?php echo $this->formLabel($this->form->get('name')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('name')); ?>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('name')); ?>
                        </section>         
                            
                        <section class="col-md-6">
                            <!-- <label class="label">Select</label> -->
                            <?php echo $this->formLabel($this->form->get('country')); ?>
                            <label class="select">
                                <?php echo $this->formSelect($this->form->get('country')); ?>
                                <i></i>
                            </label>
                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('country')); ?>
                        </section>

                        <section class="col-md-12">
                            <div class="map_canvas">
                            </div>
                        </section>
                    
                    </fieldset>
                    
                    <footer>
                        <button type="submit" class="btn-u">Next</button>
                        <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">Back</button>
                    </footer>
                <!-- </form> -->
                    <?php echo $this->form()->closeTag($form); ?>
                    <!--End Table Search v2-->
                </div>
                <!--End Profile Body-->
            </div>
<script>
    $(function(){
        
        $("#city-name").geocomplete({
            types: ['(cities)'],
            map: ".map_canvas",
        })
        .bind("geocode:result", function(event, result)
        {
            console.log(result.address_components);
            // console.log(result.address_components[0].long_name);
            // console.log(result.address_components[3].long_name);

            var countryName;

            if(result.address_components.length === 4)
            {
                countryName = result.address_components[3].long_name
            } 
            else if (result.address_components.length === 3)
            {
                countryName = result.address_components[2].long_name
            }
            else if (result.address_components.length === 2)
            {
                countryName = result.address_components[1].long_name
            }

            // console.log(countryName);

            $.log("Result: " + result);
            $.post("/registration/get-city-id", { country: countryName, }, function(data)
            {
                // console.log(data.countryId);
                // console.log(data.cityName);
                $("#city-country").val(data.countryId);
            }, 'json');

            $("#city-name").val(result.address_components[0].long_name);
        });
        
    });
</script>