            
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <a href="<?php echo $this->url('administrator/default', array('controller' => 'city', 'action' => 'create-first-step' )); ?>" class="btn-u btn-brd btn-brd-hover btn-u-dark btn-u-xs pull-left margin-bottom-20">Add City</a>

                        <br>
                        <br><br>
                    <div class="table-search-v2 margin-bottom-20">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th class="hidden-sm">Name</th>
                                        <th>Country</th>
                                        <th>Franchisors</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($cities as $city): ?>
                                    <tr>
                                        <td>
                                            <img class="rounded" src="<?php echo $filesDir . DIRECTORY_SEPARATOR . $city->getId() . DIRECTORY_SEPARATOR . 'square60x60_' . $city->getImage(); ?>" alt="">
                                        </td>
                                        <td class="td-width">
                                            <h3><a href="<?php echo $this->url('administrator/default', array('controller' => 'city', 'action' => 'view', 'id' => $city->getId())); ?>"><?php echo $city->getName(); ?></a></h3>
                                            <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id commodo lacus. Fusce non malesuada ante. Donec vel arcu.</p>
                                            <small class="hex">Joined February 28, 2014</small> -->
                                        </td>
                                        
                                        <td><?php echo $city->getCountry()->getName(); ?>
                                            <!-- <ul class="list-inline s-icons">
                                                <li>
                                                    <a data-placement="top" data-toggle="tooltip" class="tooltips" data-original-title="Facebook" href="#">
                                                        <i class="fa fa-facebook"></i>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a data-placement="top" data-toggle="tooltip" class="tooltips" data-original-title="Twitter" href="#">
                                                        <i class="fa fa-twitter"></i>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a data-placement="top" data-toggle="tooltip" class="tooltips" data-original-title="Dropbox" href="#">
                                                    <i class="fa fa-dropbox"></i>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a data-placement="top" data-toggle="tooltip" class="tooltips" data-original-title="Linkedin" href="#">
                                                        <i class="fa fa-linkedin"></i>
                                                    </a>
                                                </li> 
                                            </ul>
                                            <span><a href="#">info@example.com</a></span>
                                            <span><a href="#">www.htmlstream.com</a></span>-->
                                        </td>
                                        <td>
                                            <span class="label label-success">Success</span>
                                        </td>
                                    </tr>
                                     <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>    
                    </div>
                </div>
                <!--End Profile Body-->
            </div>