<div class="breadcrumbs">
    <div class="container">
        <h1 class="pull-left">Partner</h1>
        <ul class="pull-right breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Partner</li>
        </ul>
    </div>
</div>

<div class="container content">		
    	<div class="row margin-bottom-40">
        	<div class="col-md-6 md-margin-bottom-40">
                <p>Fryday is an international network of cosmopolitan professionals present in 30 cities in 20+ countries and has 150k+ registered members.  Fryday offers unique networking opportunities in a truly international environment. </p>
                <p>Fryday has several opportunities for companies that want to communicate with or meet Fryday’s 150,000 members in 20+ countries.</p>
                <p>Fryday can offer advertisers:</p>
                <ul class="list-unstyled">
                    <li><i class="fa fa-check color-green"></i> Space in newsletters in one or several of Fryday’s 30 communities.</li>
                    <li><i class="fa fa-check color-green"></i> Space on Fryday.net.</li>
                    <li><i class="fa fa-check color-green"></i> Presence in Fryday’s social media groups, videos, photos etc.</li>
                </ul>
                <p>Fryday’s members are:</p>
                <ul class="list-unstyled">
                    <li><i class="fa fa-check color-green"></i> International</li>
                    <li><i class="fa fa-check color-green"></i> Higher income persons</li>
                    <li><i class="fa fa-check color-green"></i> Decision makers</li>
                    <li><i class="fa fa-check color-green"></i> Company owners</li>
                    <li><i class="fa fa-check color-green"></i> Active consumers</li>
                </ul>
                <p>Sponsors support Fryday as they are interested in reaching an exclusive group of people and forming a relationship with them. The key argument for sponsors is that Fryday’s guests are relevant and senior enough to make decisions. Sponsors also appreciate to be featured by Fryday’s media partners as well as getting great exposure in the digital media Fryday controls.</p>
                <p>Please contact Fryday for a detailed proposal that meets your requirements.<br> info@fryday.net </p>
                <br>
            </div>

        	<div class="col-md-6 md-margin-bottom-40">
                <div class="responsive-video">
                	<iframe src="//www.youtube.com/embed/YT7UYJJdUQY" frameborder="0" allowfullscreen></iframe>
                   	<!--  <iframe src="http://player.vimeo.com/video/9679622" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" frameborder="0"></iframe>  -->
                </div>
            </div>
        </div><!--/row-->

    	
    </div>