<div class="profile container content">
    	<div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <img class="img-responsive profile-img margin-bottom-20" src="<?php echo '/uploads/users' . DIRECTORY_SEPARATOR . $this->identity()->getId() . DIRECTORY_SEPARATOR . 'square264x264_' . $this->identity()->getImage(); ?>" alt="">
                <?php echo $this->navigation('admin_navigation')->menu()->setUlClass('list-group sidebar-nav-v1 margin-bottom-40')->setAddClassToListItem(true)->escapeLabels(false); ?>
                <hr>
            </div>
            <!--End Left Sidebar-->
            
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <!--Table Search v2-->
                    <?php $form->setAttribute('action', $this->url('administrator_content/default', array('controller' => 'venue', 'action' => 'create')))->prepare(); ?>
                    <?php echo $this->form()->openTag($form); ?>
                    <!-- <form action="" class="sky-form"> -->
                    <header>Create New Venue</header>
                    
                    <fieldset>
                        <section>
                            <?php echo $this->formLabel($this->form->get('name')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('name')); ?>
                            </label>
                        </section>

                        <section>
                            <?php echo $this->formLabel($this->form->get('profileImage')); ?>
                            <label for="file" class="input input-file">
                                <div class="button">
                                    <?php echo $this->formFile($this->form->get('profileImage')); ?>
                                    Browse
                                </div>
                                <input readonly="" type="text">
                                <?php //echo $this->formFile($this->form->get('profileImage')); ?>
                            </label>
                        </section>              
                            
                         <?php if ($this->identity()->getRole()->getName() == 'administrator'): ?>
                            <section>
                                <!-- <label class="label">Select</label> -->
                                <?php echo $this->formLabel($this->form->get('city')); ?>
                                <label class="select">
                                    <?php echo $this->formSelect($this->form->get('city')); ?>
                                    <i></i>
                                </label>
                            </section>
                        <?php endif; ?>
                    </fieldset>

                    <fieldset>
                        <section>
                            <?php echo $this->formLabel($this->form->get('phone')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('phone')); ?>
                            </label>
                        </section>

                        <section>
                            <?php echo $this->formLabel($this->form->get('website')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('website')); ?>
                            </label>
                        </section>

                        <section>
                            <?php echo $this->formLabel($this->form->get('email')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('email')); ?>
                            </label>
                        </section>

                        <section>
                            <?php echo $this->formLabel($this->form->get('address')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('address')); ?>
                            </label>
                        </section>
                    </fieldset>

                    <footer>
                        <button type="submit" class="btn-u">Submit</button>
                        <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">Back</button>
                    </footer>
                <!-- </form> -->
                    <?php echo $this->form()->closeTag($form); ?>
                    <!--End Table Search v2-->
                </div>
                <!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div>