<div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <!--Table Search v2-->
                    <?php $form->setAttribute('action', $this->url('administrator/default', array('controller' => 'venue', 'action' => 'edit', 'id' => $venue->getId())))->prepare(); ?>
                    <?php echo $this->form()->openTag($form); ?>
                    <!-- <form action="" class="sky-form"> -->
                    <header>Add Venue. Step 2</header>
                    
                    <fieldset>
                        <section class="col-md-12">
                            <?php echo $this->formLabel($this->form->get('name')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('name')); ?>
                            </label>

                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('name')); ?>
                        </section>

                            <?php if($venue->getImage() != null): ?>
                            <div class="col-md-12 imag_center">
                                <img style="max-height: 320px;max-width: 640px; "id="imagepreview" src="<?php echo $currentUploadDir . DIRECTORY_SEPARATOR . $venue->getImage(); ?>" alt="your image" />
                            </div>
                            <?php else: ?>
                            <div class="col-md-12 imag_center">
                                <img style="max-height: 320px;max-width: 640px; "id="imagepreview" src="/frontend/img/noimage.png" alt="your image" />
                            </div>
                            <?php endif; ?>
                        
                        <section class="col-md-6">
                            <!-- <label class="label">File input</label>/ -->
                            <?php echo $this->formLabel($this->form->get('image')); ?>
                            <label for="file" class="input input-file">
                                <div class="button">
                                    <!-- <input id="file" onchange="this.parentNode.nextSibling.value = this.value" type="file"> -->
                                    <?php echo $this->formFile($this->form->get('image')); ?>
                                    Browse
                                </div>
                                <input readonly="" type="text">
                                <?php //echo $this->formFile($this->form->get('profileImage')); ?>
                            </label>
                            <?php echo $this->formInput($this->form->get('xStartCrop')); ?>
                            <?php echo $this->formInput($this->form->get('yStartCrop')); ?>
                            <?php echo $this->formInput($this->form->get('widthCrop')); ?>
                            <?php echo $this->formInput($this->form->get('heightCrop')); ?>
                            <?php echo $this->formInput($this->form->get('widthCurrent')); ?>
                            <?php echo $this->formInput($this->form->get('heightCurrent')); ?>

                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('image')); ?>
                        </section>

                        <section class="col-md-6">
                            <?php echo $this->formLabel($this->form->get('city')); ?>
                            <label class="select">
                                <?php echo $this->formSelect($this->form->get('city')); ?>
                            </label>

                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('city')); ?>
                        </section>

                        <section class="col-md-12">
                            <?php echo $this->formLabel($this->form->get('address')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('address')); ?>
                            </label>

                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('address')); ?>
                        </section>

                        <section class="col-md-12">
                            <div class="map_canvas">
                            </div>
                        </section>

                        <section class="col-md-6">
                            <?php echo $this->formLabel($this->form->get('website')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('website')); ?>
                            </label>

                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('website')); ?>
                        </section>

                        <section class="col-md-6">
                            <?php echo $this->formLabel($this->form->get('email')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('email')); ?>
                            </label>

                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('email')); ?>
                        </section>

                        <section class="col-md-6">
                            <?php echo $this->formLabel($this->form->get('phone')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('phone')); ?>
                            </label>

                            <?php echo $this->formElementErrors()->setMessageOpenFormat('<div class="note note-error">')->setMessageSeparatorString('</div><div class="note note-error">')->setMessageCloseString('</div>')->render($this->form->get('phone')); ?>
                        </section>

                    </fieldset>
                    
                    <footer>
                        <button type="submit" class="btn-u">Save</button>
                        <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">Back</button>
                    </footer>
                <!-- </form> -->
                    <?php echo $this->form()->closeTag($form); ?>
                    <!--End Table Search v2-->
                </div>
                <!--End Profile Body-->
            </div>
    <script>

    function readURL(input) 
    {
        if (input.files && input.files[0]) 
        {
            var reader = new FileReader();

            reader.onload = function (e) 
            {
                $('#imagepreview').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $(document).ready(function () {
        $('#imagepreview').imgAreaSelect({ 
            // maxWidth: 200, 
            // maxHeight: 150, 
            aspectRatio: '2:1',
            handles: true,
            // show: true,
            onSelectChange: preview,
            x1: parseInt($('#x-start-crop').val(), 10),
            y1: parseInt($('#y-start-crop').val(), 10),
            x2: parseInt($('#x-start-crop').val(), 10) + parseInt($('#width-crop').val(), 10),
            y2: parseInt($('#y-start-crop').val(), 10) + parseInt($('#height-crop').val(), 10),
        });
    });

    $("#venue-image").change(function(){
        readURL(this);
    });

    function preview(img, selection) {  
        $('#width-current').val(img.clientWidth);  
        $('#height-current').val(img.clientHeight);  
        $('#x-start-crop').val(selection.x1);  
        $('#y-start-crop').val(selection.y1); 
        $('#width-crop').val(selection.width);  
        $('#height-crop').val(selection.height);
    }
    </script>

    <script>
    $(function(){
        
        $("#venue-address").geocomplete({
            // types: ['(cities)'],
            map: ".map_canvas",
            location: <?php echo json_encode($address); ?>,
        })
        .bind("geocode:result", function(event, result)
        {
            console.log(result.address_components);
            // console.log(result.address_components[0].long_name);
            // console.log(result.address_components[3].long_name);
        });
        
    });
</script>