<div class="profile container content">
    	<div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <?php if($this->identity()->getImage() != null): ?>
                <img class="img-responsive profile-img margin-bottom-20" src="<?php echo '/uploads/users' . DIRECTORY_SEPARATOR . $this->identity()->getId() . DIRECTORY_SEPARATOR . 'square264x264_' . $this->identity()->getImage(); ?>" alt="<?php echo $this->identity()->getFirstName() . " " . $this->identity()->getLastName(); ?>">
                <?php else: ?>
                <img class="img-responsive md-margin-bottom-10" src="/frontend/img/noavatar.png" alt="<?php echo $this->identity()->getFirstName() . " " . $this->identity()->getLastName(); ?>">
                <?php endif; ?>
                <?php echo $this->navigation('admin_navigation')->menu()->setUlClass('list-group sidebar-nav-v1 margin-bottom-40')->setAddClassToListItem(true)->escapeLabels(false); ?>
                <hr>
            </div>
            <!--End Left Sidebar-->
            
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <?php if(count($flashMessages)) : ?>
                    <div class="alert alert-success fade in">
                        <?php foreach ($flashMessages as $msg) : ?>
                        <?php echo $msg; ?> <br>
                        <?php endforeach; ?>
                    </div>
                    <?php endif; ?>
                    <a href="<?php echo $this->url('administrator_content/default', array('controller' => 'venue', 'action' => 'create-first-step' )); ?>" class="btn-u btn-brd btn-brd-hover btn-u-dark btn-u-xs pull-left margin-bottom-20">Add Venue</a>
                    <div class="table-search-v2 margin-bottom-20">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Profile Image</th>
                                        <th class="hidden-sm">Name</th>
                                        <th>City</th>
                                        <th>Contacts</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($venues as $venue): ?>
                                    <tr>
                                        <td>
                                            <img class="rounded" src="<?php echo $filesDir . DIRECTORY_SEPARATOR . $venue->getId() . DIRECTORY_SEPARATOR . 'square60x60_' . $venue->getImage(); ?>" alt="">
                                        </td>
                                        <td class="td-width">
                                            <h3><a href="#"><?php echo $venue->getName(); ?></a></h3>
                                            <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id commodo lacus. Fusce non malesuada ante. Donec vel arcu.</p>
                                            <small class="hex">Joined February 28, 2014</small> -->
                                        </td>
                                        <!-- <td>
                                            <span class="label label-success">Success</span>
                                        </td> -->
                                        <td><?php echo $venue->getCity()->getName(); ?></td> 
                                            <!-- <ul class="list-inline s-icons">
                                                <li>
                                                    <a data-placement="top" data-toggle="tooltip" class="tooltips" data-original-title="Facebook" href="#">
                                                        <i class="fa fa-facebook"></i>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a data-placement="top" data-toggle="tooltip" class="tooltips" data-original-title="Twitter" href="#">
                                                        <i class="fa fa-twitter"></i>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a data-placement="top" data-toggle="tooltip" class="tooltips" data-original-title="Dropbox" href="#">
                                                    <i class="fa fa-dropbox"></i>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a data-placement="top" data-toggle="tooltip" class="tooltips" data-original-title="Linkedin" href="#">
                                                        <i class="fa fa-linkedin"></i>
                                                    </a>
                                                </li> 
                                            </ul>-->
                                        <td>
                                        	<span><a href="#"><?php echo $venue->getPhone(); ?></a></span>
                                            <span><a href="#"><?php echo $venue->getEmail(); ?></a></span>
                                            <span><a href="#"><?php echo $venue->getWebsite(); ?></a></span>
                                        </td>
                                    </tr>
                                     <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>    
                    </div>
                </div>
                <!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div>