<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/font-awesome-4.1.0/css/font-awesome.min.css')
            ->prependStylesheet($this->basePath() . '/css/plugins/morris.css')
            ->prependStylesheet($this->basePath() . '/css/sb-admin-2.css')
            ->prependStylesheet($this->basePath() . '/css/plugins/timeline.css')
            ->prependStylesheet($this->basePath() . '/css/plugins/metisMenu/metisMenu.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/myscript.js')
            ->prependFile($this->basePath() . '/js/jquery.tweet.js')
            ->prependFile($this->basePath() . '/js/jquery.jcarousel.js')
            ->prependFile($this->basePath() . '/js/greyScale.js')
            ->prependFile($this->basePath() . '/js/jquery.prettyPhoto.js')
            ->prependFile($this->basePath() . '/js/superfish.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/camera.js')
            ->prependFile($this->basePath() . '/js/jquery.mobile.customized.min.js')
            ->prependFile($this->basePath() . '/js/jquery.easing.1.3.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div id="wrapper">
            <?php echo $this->content; ?>
        </div>
    </body>
</html>
