<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('FRYDAY '. $this->translate('One Of The Largest Networks Of Cosmopolitan Professionals'))->setSeparator(' - ')->setAutoEscape(false) 
        ; ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ; ?>

        <!-- STYLES -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        
            ->prependStylesheet($this->basePath() . '/frontend/plugins/datetimepicker/jquery.datetimepicker.css')
            ->prependStylesheet($this->basePath() . '/frontend/css/custom.css')
            ->prependStylesheet($this->basePath() . '/frontend/css/themes/default.css')
            ->prependStylesheet($this->basePath() . '/frontend/css/pages/profile.css')
            ->prependStylesheet($this->basePath() . '/frontend/css/pages/page_log_reg_v1.css')
            ->prependStylesheet($this->basePath() . '/frontend/css/pages/page_clients.css')
            ->prependStylesheet($this->basePath() . '/frontend/css/pages/page_search.css')
            ->prependStylesheet($this->basePath() . '/frontend/plugins/sky-forms/version-2.0.1/css/custom-sky-forms.css')
            ->prependStylesheet($this->basePath() . '/frontend/plugins/sky-forms/version-2.0.1/css/sky-forms.css')
            ->prependStylesheet($this->basePath() . '/frontend/plugins/parallax-slider/css/parallax-slider.css')
            ->prependStylesheet($this->basePath() . '/frontend/plugins/flexslider/flexslider.css')
            ->prependStylesheet($this->basePath() . '/frontend/plugins/font-awesome/css/font-awesome.min.css')
            ->prependStylesheet($this->basePath() . '/frontend/plugins/line-icons/line-icons.css')
            ->prependStylesheet($this->basePath() . '/frontend/css/style.css')
            ->prependStylesheet($this->basePath() . '/frontend/plugins/bootstrap/css/bootstrap.min.css')
        ; ?>

        <!-- SCRIPTS -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/frontend/js/plugins/validation.js')
            ->prependFile($this->basePath() . '/frontend/js/plugins/datepicker.js')
            ->prependFile($this->basePath() . '/frontend/js/plugins/masking.js')
            //->prependFile($this->basePath() . '/frontend/js/pages/index.js')
            ->prependFile($this->basePath() . '/frontend/js/app.js')
            ->prependFile($this->basePath() . '/frontend/plugins/datetimepicker/jquery.datetimepicker.js')
            // ->prependFile($this->basePath() . '/frontend/plugins/datetimepicker/jquery.js')
            ->prependFile($this->basePath() . '/frontend/plugins/sky-forms/version-2.0.1/js/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/frontend/plugins/sky-forms/version-2.0.1/js/jquery.maskedinput.min.js')
            ->prependFile($this->basePath() . '/frontend/plugins/sky-forms/version-2.0.1/js/jquery.validate.min.js')
            //->prependFile($this->basePath() . '/frontend/plugins/jquery-ui-1.11.2/jquery-ui.js')
            //->prependFile($this->basePath() . '/frontend/plugins/parallax-slider/js/jquery.cslider.js')           
            //->prependFile($this->basePath() . '/frontend/plugins/parallax-slider/js/modernizr.js')
            //->prependFile($this->basePath() . '/frontend/plugins/flexslider/jquery.flexslider-min.js')
            ->prependFile($this->basePath() . '/frontend/plugins/back-to-top.js')
            ->prependFile($this->basePath() . '/frontend/plugins/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/frontend/plugins/jquery-migrate-1.2.1.min.js')
            // ->prependFile($this->basePath() . '/frontend/plugins/jquery-1.10.2.min.js')
            ->prependFile($this->basePath() . '/frontend/plugins/datetimepicker/jquery.datetimepicker.js')
            ->prependFile($this->basePath() . '/frontend/plugins/datetimepicker/jquery.js')
            //->prependFile($this->basePath() . 'http://www.google-analytics.com/ga.js')
        ; ?>

    </head>
    <body>
        <div class="wrapper">
            <div class="header">
                <!-- Topbar -->
                <div class="topbar">
                    <div class="container">
                        <!-- Topbar Navigation -->
                        <ul class="loginbar pull-right">
                            <li>
                                <i class="fa fa-globe"></i>
                                <a>Choose Your City</a>
                                <ul class="lenguages">
<!--                                     <li class="active">
                                        <a href="#">Kiyv <i class="fa fa-check"></i></a> 
                                    </li> -->
                                    <li><a href="#">Kyiv</a></li>
                                    <li><a href="#">Praga</a></li>
                                    <li><a href="#">Tbilisi</a></li>
                                    <li><a href="#">German</a></li>
                                </ul>
                            </li>
                            <li class="topbar-devider"></li>   
                            <li><a href="page_faq.html">Registration</a></li>  
<!--                            <li class="topbar-devider"></li>   
                            <li><a href="page_login.html">Login</a></li>   --> 
                        </ul>
                        <!-- End Topbar Navigation -->
                    </div>
                </div>
                <!-- End Topbar -->
            
                <!-- Navbar -->
                <div class="navbar navbar-default" role="navigation">
                    <div class="container">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="fa fa-bars"></span>
                            </button>
                            <a class="navbar-brand" href="index.html">
                                <img id="logo-header" src="/frontend/img/logo_fryday.jpg" width="200px" alt="Logo">
                            </a>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse navbar-responsive-collapse">
                            <?php
                                echo $this->navigation('frontend_navigation')->menu()->setUlClass('nav navbar-nav');
                                // The first variant of rendering
                                // echo $this->navigation('navigation')->menu()->setMaxDepth(1)->setMinDepth(1)->setOnlyActiveBranch(true)->setUlClass('nav nav-tabs');
                                // The second variant via options
                                //echo $this->navigation('navigation')->menu()->renderMenu(null, array('ulClass' => 'nav nav-tabs', 'minDepth' => 1, 'maxDepth' => 1, 'onlyActiveBranch'  => true));
                            ?>
                            <!-- <ul class="nav navbar-nav">
                                <li>
                                    <a href="/">
                                        Home
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        Franchise
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        Advertise
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        Partner
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        Media
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        Member
                                    </a>
                                </li>
                                <li class="active">
                                    <a href="javascript:void(0);">
                                        Venue
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        Speaker
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        About
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        Contact
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        Event
                                    </a>
                                </li>
                            </ul> -->
                        </div><!--/navbar-collapse-->
                    </div>    
                </div>            
                <!-- End Navbar -->
            </div>

            <?php echo $this->content; ?>

    
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4 md-margin-bottom-40">
                    <!-- About -->
                    <div class="headline"><h2>About</h2></div>  
                    <p class="margin-bottom-25 md-margin-bottom-40">Fryday is one of the largest networking clubs for professionals organising series of social and business networking events across Eastern Europe and Central Asia.</p>    
                    <!-- End About -->

                    <!-- Monthly Newsletter -->
                    <div class="headline"><h2>Newsletter</h2></div> 
                    <p>Subscribe to our newsletter and stay up to date with the all events!</p>
                    <form class="footer-subsribe">
                        <div class="input-group">
                            <input class="form-control" placeholder="Email Address" type="text">                            
                            <span class="input-group-btn">
                                <button class="btn-u" type="button">Subscribe</button>
                            </span>
                        </div>                  
                    </form>                         
                    <!-- End Monthly Newsletter -->
                </div><!--/col-md-4-->  
                
                <div class="col-md-4 md-margin-bottom-40">
                    <!-- Recent Blogs -->
                    <div class="posts">
                        <div class="headline"><h2>Upcoming Events</h2></div>
                        <dl class="dl-horizontal">
                            <dt><a href="#"><img src="/frontend/img/sliders/elastislide/6.jpg" alt=""></a></dt>
                            <dd>
                                <p><a href="#">Anim moon officia Unify is an incredibly beautiful responsive Bootstrap Template</a></p> 
                            </dd>
                        </dl>
                        <dl class="dl-horizontal">
                        <dt><a href="#"><img src="/frontend/img/sliders/elastislide/10.jpg" alt=""></a></dt>
                            <dd>
                                <p><a href="#">Anim moon officia Unify is an incredibly beautiful responsive Bootstrap Template</a></p> 
                            </dd>
                        </dl>
                        <dl class="dl-horizontal">
                        <dt><a href="#"><img src="/frontend/img/sliders/elastislide/11.jpg" alt=""></a></dt>
                            <dd>
                                <p><a href="#">Anim moon officia Unify is an incredibly beautiful responsive Bootstrap Template</a></p> 
                            </dd>
                        </dl>
                    </div>
                    <!-- End Recent Blogs -->                    
                </div><!--/col-md-4-->

                <div class="col-md-4">
                    <!-- Contact Us -->
                    <div class="headline"><h2>Contact Us</h2></div> 
                    <address class="md-margin-bottom-40">
                        25, Lorem Lis Street, Orange <br>
                        California, US <br>
                        Phone: +3 <br>
                        Fax: 800 123 3456 <br>
                        Email: <a href="mailto:info@anybiz.com" class="">info@fryday.net</a>
                    </address>
                    <!-- End Contact Us -->

                    <!-- Social Links -->
                    <div class="headline"><h2>Stay Connected</h2></div> 
                    <ul class="social-icons">
                        <li><a href="#" data-original-title="Feed" class="social_rss"></a></li>
                        <li><a href="#" data-original-title="Facebook" class="social_facebook"></a></li>
                        <li><a href="#" data-original-title="Twitter" class="social_twitter"></a></li>
                        <li><a href="#" data-original-title="Goole Plus" class="social_googleplus"></a></li>
                        <li><a href="#" data-original-title="Pinterest" class="social_pintrest"></a></li>
                        <li><a href="#" data-original-title="Linkedin" class="social_linkedin"></a></li>
                        <li><a href="#" data-original-title="Vimeo" class="social_vimeo"></a></li>
                    </ul>
                    <!-- End Social Links -->
                </div><!--/col-md-4-->
            </div>
        </div> 
    </div>
    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-6">                     
                    <p>
                        2014 © Fryday. ALL Rights Reserved. 
                        <a target="_blank" href="https://twitter.com/htmlstream">Htmlstream</a> | <a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a>
                    </p>
                </div>
<!--                 <div class="col-md-6">  
                    <a href="index.html">
                        <img class="pull-right" id="logo-footer" src="/frontend/img/logo2-default.png" alt="">
                    </a>
                </div> -->
            </div>
        </div> 
    </div>
        <script type="text/javascript">
            jQuery(document).ready(function() {
                App.init();
                Masking.initMasking();
                Datepicker.initDatepicker();
                Validation.initValidation();
            });
        </script>
        <script type="text/javascript">
            // jQuery(document).ready(function() {
            //     App.init();
            //     App.initSliders();        
            // });
        </script>
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-29166220-1']);
          _gaq.push(['_setDomainName', 'htmlstream.com']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); 
            ga.type = 'text/javascript'; 
            ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; 
            s.parentNode.insertBefore(ga, s);
          })();
        </script>

    </body>
    <script>
    // $(function() {
        $('#datetimepicker').datetimepicker({
            value:'2015/04/15 05:03',
            formatTime:'H:i',
            formatDate:'d.m.Y',
        });
        $('#datetimepicker1').datetimepicker({
            value:'2015/04/15 05:03',
            formatTime:'H:i',
            formatDate:'d.m.Y',
        });
    // });
</script>
</html>