<div class="profile container content">
    	<div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <img class="img-responsive profile-img margin-bottom-20" src="<?php echo $this->identity()->getProfileImage(); ?>" alt="">
                <?php echo $this->navigation('admin_navigation')->menu()->setUlClass('list-group sidebar-nav-v1 margin-bottom-40')->setAddClassToListItem(true)->escapeLabels(false); ?>
                <hr>
            </div>
            <!--End Left Sidebar-->
            
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <!--Table Search v2-->
                    <?php $form->setAttribute('action', $this->url('administrator_content/default', array('controller' => 'event', 'action' => 'create')))->prepare(); ?>
                    <?php echo $this->form()->openTag($form); ?>
                    <!-- <form action="" class="sky-form"> -->
                    <header>Create New Event</header>
                    
                    <fieldset>
                        <section>
                            <?php echo $this->formLabel($this->form->get('title')); ?>
                            <label class="input">
                                <?php echo $this->formInput($this->form->get('title')); ?>
                            </label>
                        </section>
                        
                        <section>
                            <!-- <label class="label">Textarea</label> -->
                            <?php echo $this->formLabel($this->form->get('description')); ?>
                            <label class="textarea">
                                <?php echo $this->formTextarea($this->form->get('description')); ?>
                            </label>
                        </section>

                        <div class="row">
                            <section class="col col-4">
                                <!-- <label class="label">Name</label> -->
                                <?php echo $this->formLabel($this->form->get('date')); ?>
                                <label class="input">
                                    <i class="icon-append fa fa-calendar"></i>
                                    <!-- <input name="name" id="name" type="text"> -->
                                    <?php echo $this->formInput($this->form->get('date')); ?>
                                </label>
                            </section>
                            <section class="col col-4">
                                <!-- <label class="label">E-mail</label> -->
                                <?php echo $this->formLabel($this->form->get('time')); ?>
                                <label class="input">
                                    <i class="icon-append fa fa-clock-o"></i>
                                    <!-- <input name="email" id="email" type="email"> -->
                                    <?php echo $this->formInput($this->form->get('time')); ?>
                                </label>
                            </section>
                            <section class="col col-4">
                                <!-- <label class="label">Select</label> -->
                                <?php echo $this->formLabel($this->form->get('venue')); ?>
                                <label class="select">
                                    <?php echo $this->formSelect($this->form->get('venue')); ?>
                                    <i></i>
                                </label>
                            </section>
                        </div>

                        <section>
                            <?php echo $this->formLabel($this->form->get('profileImage')); ?>
                            <label for="file" class="input input-file">
                                <div class="button">
                                    <?php echo $this->formFile($this->form->get('profileImage')); ?>
                                    Browse
                                </div>
                                <input readonly="" type="text">
                                <?php //echo $this->formFile($this->form->get('profileImage')); ?>
                            </label>
                        </section>              
                            
                        <section>
                            <!-- <label class="label">Textarea</label> -->
                            <?php echo $this->formLabel($this->form->get('details')); ?>
                            <label class="textarea">
                                <?php echo $this->formTextarea($this->form->get('details')); ?>
                            </label>
                        </section>
                    </fieldset>

                    <footer>
                        <button type="submit" class="btn-u">Submit</button>
                        <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">Back</button>
                    </footer>
                <!-- </form> -->
                    <?php echo $this->form()->closeTag($form); ?>
                    <!--End Table Search v2-->
                </div>
                <!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div>

<script>
    // $(function() {
    //     $( "#datepicker" ).datepicker({
    //         prevText: '<i class="fa fa-angle-left"></i>',
    //         nextText: '<i class="fa fa-angle-right"></i>'
    //     });
    // });
    $('#event-date').datepicker({
        prevText: '<i class="fa fa-angle-left"></i>',
        nextText: '<i class="fa fa-angle-right"></i>',
    });
    $('#event-time').datetimepicker({
        format:'H:i',
        datepicker:false,
    });
</script>
