<div class="profile container content">
    	<div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <img class="img-responsive profile-img margin-bottom-20" src="assets/img/team/5.jpg" alt="">
                <?php echo $this->navigation('admin_navigation')->menu()->setUlClass('list-group sidebar-nav-v1 margin-bottom-40')->setAddClassToListItem(true)->escapeLabels(false); ?>
                <hr>
            </div>
            <!--End Left Sidebar-->
            
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">

                    <div class="table-search-v1 margin-bottom-20">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th class="hidden-sm">Title</th>
                                        <th>City</th>
                                        <th>Venue</th>
                                        <th>User</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($events as $event): ?>
                                    <tr>
                                        <td>
                                            <div class="date-formats-index-events-list">
                                                <span><?php echo $event->getDateTimeEvent()->format('d'); ?></span>
                                                <small><?php echo $event->getDateTimeEvent()->format('n'); ?>, <?php echo $event->getDateTimeEvent()->format('Y'); ?></small>
                                            </div>
                                        </td>
                                        <td class="td-width">
                                            <h3><a href="#"><?php echo $event->getTitle(); ?></a></h3>
                                            <?php echo $event->getDescription(); ?>
                                            <span class="date-time-created-events-list-admin">Created <?php echo $event->getDateTimeCreated()->format('F j, Y'); ?></span>
                                        </td>
                                        <td  class="hidden-sm">
                                            <div class="m-marker">
                                                <a href="#"><i class="color-green fa fa-map-marker"></i></a>
                                                <a href="#" class="display-b"><?php echo $event->getVenue()->getCity()->getCountry()->getName(); ?></a>
                                                <a href="#"><?php echo $event->getVenue()->getCity()->getName(); ?></a>
                                            </div>
                                        <td>
                                        	<span><a href="#"><?php echo $event->getVenue()->getName(); ?></a></span>
                                        </td>
                                        <td>
                                            <span><a href="#"><?php echo $event->getUser()->getFirstName(); ?> <?php echo $event->getUser()->getLastName(); ?></a></a></span>
                                        </td>
                                    </tr>
                                     <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>    
                    </div>
                </div>
                <!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div>