<div class="profile container content">
    	<div class="row">
            
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <?php if($this->identity()->getImage() != null): ?>
                <img class="img-responsive profile-img margin-bottom-20" src="<?php echo '/uploads/users' . DIRECTORY_SEPARATOR . $this->identity()->getId() . DIRECTORY_SEPARATOR . 'square264x264_' . $this->identity()->getImage(); ?>" alt="<?php echo $this->identity()->getFirstName() . " " . $this->identity()->getLastName(); ?>">
                <?php else: ?>
                <img class="img-responsive md-margin-bottom-10" src="/frontend/img/noavatar.png" alt="<?php echo $this->identity()->getFirstName() . " " . $this->identity()->getLastName(); ?>">
                <?php endif; ?>
                <?php echo $this->navigation('admin_navigation')->menu()->setUlClass('list-group sidebar-nav-v1 margin-bottom-40')->setAddClassToListItem(true)->escapeLabels(false); ?>
                <hr>
            </div>
            <!--End Left Sidebar-->
            
            <div class="col-md-9">
                <!--Profile Body-->
                <div class="profile-body">
                    <div class="row margin-bottom-20">
                        <div class="col-sm-6 sm-margin-bottom-20">
                            <div class="service-block-v3 service-block-u">
                                <i class="icon-users"></i>
                                <span class="service-heading">Overall Subscribers</span>
                                <span class="counter"><?php echo number_format($overallSubscribers); ?></span> 
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="service-block-v3 service-block-blue">
                                <i class="icon-globe"></i>
                                <span class="service-heading">Overall Cities</span>
                                <span class="counter"><?php echo number_format($overallCities); ?></span> 
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row margin-bottom-30"> 
                        <div class="col-md-4 sm-margin-bottom-20">
                            <form action="<?php echo $this->url('administrator_content/default', array('controller' => 'event', 'action' => 'create-first-step' )); ?>">
                                <input class="btn-u btn-u-lg btn-block btn-u-dark-blue" type="submit" value="Create Event">
                            </form>
                        </div>
                        <div class="col-md-4 sm-margin-bottom-20">
                            <form action="<?php echo $this->url('administrator_content/default', array('controller' => 'partner', 'action' => 'create-first-step' )); ?>">
                                <input class="btn-u btn-u-lg btn-block btn-u-dark-blue" type="submit" value="Add Partner">
                            </form>
                        </div>
                        <div class="col-md-4 sm-margin-bottom-20">
                            <form action="<?php echo $this->url('administrator_content/default', array('controller' => 'venue', 'action' => 'create-first-step' )); ?>">
                                <input class="btn-u btn-u-lg btn-block btn-u-dark-blue" type="submit" value="Add Venue">
                            </form>
                        </div>
                    </div>
                    <!--End Service Block v3-->
                </div>
                <!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div>
<script>
    jQuery(document).ready(function ($) {
        "use strict";
        $('.contentHolder').perfectScrollbar();
    });
</script>

<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init();
        App.initCounter();
        Datepicker.initDatepicker();
        StyleSwitcher.initStyleSwitcher();      
    });
</script>