<div class="breadcrumbs">
        <div class="container">
            <h1 class="pull-left">Login</h1>
            <ul class="pull-right breadcrumb">
                <li><a href="index.html">Home</a></li>
                <li class="active">Login</li>
            </ul>
        </div><!--/container-->
    </div>
<div class="container content">		
    	<div class="row">
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
            	<?php $form->setAttribute('action', $this->url('administrator_login'))->prepare(); ?>
                <?php echo $this->form()->openTag($form); ?>
                <!-- <form class="reg-page"> -->
                    <div class="reg-header">            
                        <h2>Login to your account</h2>
                    </div>
		    		
	                    <div class="input-group margin-bottom-20">
	                        <span class="input-group-addon"><i class="fa fa-at"></i></span>
	                        <!-- <input placeholder="Username" class="form-control" type="text"> -->
							<?php echo $this->formInput($this->form->get('email')); ?>
	                        <?php echo $this->FormElementErrors($this->form->get('email')); ?>
	                    </div>                    
	                    <div class="input-group margin-bottom-20">
	                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
	                        <!-- <input placeholder="Password" class="form-control" type="password"> -->
							<?php echo $this->formInput($this->form->get('password')); ?>
	                        <?php echo $this->FormElementErrors($this->form->get('password')); ?>
	                    </div>                    

	                    <div class="row">
	                        <div class="col-md-6">
	                            <label class="checkbox"><input type="checkbox"> Stay signed in</label>                        
	                        </div>
	                        <div class="col-md-6">
	                            <!-- <button class="btn-u pull-right" type="submit">Login</button> -->
	                            <?php echo $this->formSubmit($this->form->get('submit')); ?>
	                        </div>
	                    </div>

	                    <hr>

	                    <h4>Forget your Password ?</h4>
	                    <p>no worries, <a class="color-green" href="#">click here</a> to reset your password.</p>
                    <?php echo $this->form()->closeTag($form); ?>
                <!-- </form>             -->
            </div>
        </div><!--/row-->
    </div>