<div class="row">
	<div class="col-lg-4">
		<div class="panel panel-default">
			<div class="panel-heading">
			    <h3 class="panel-title"><i class="fa fa-map-marker fa-fw"></i> Citites</h3>
			</div>
			<div class="panel-body">
				<a href="<?php echo $this->url('backend/default', array('controller' => 'venue', 'action' => 'create')); ?>">
					Kyiv
				</a>
<!-- 				<br>
				<a href="<?php echo $this->url('backend/default', array('controller' => 'venue', 'action' => 'index')); ?>">
					List All Venues
				</a> -->
			</div>
		</div>
	</div>

	<div class="col-lg-4">
		<div class="panel panel-default">
			<div class="panel-heading">
			    <h3 class="panel-title">Fast Links</h3>
			</div>
			<div class="panel-body">
				<a href="<?php echo $this->url('backend/default', array('controller' => 'venue', 'action' => 'create')); ?>">
					Add Venue
				</a>
				<br>
				<a href="<?php echo $this->url('backend/default', array('controller' => 'venue', 'action' => 'index')); ?>">
					List All Venues
				</a>
			</div>
		</div>
	</div>

	<div class="col-lg-4">
		<div class="panel panel-default">
			<div class="panel-heading">
			    <h3 class="panel-title"><i class="fa fa-bar-chart fa-fw"></i> Statistics</h3>
			</div>
			<div class="panel-body">
			    Panel content
			</div>
		</div>
	</div>
</div>