<div class="row">
	<div class="col-lg-4 col-lg-offset-4">
		<br><br><br><br>
		<div class="panel panel-default">
		  	<div class="panel-heading">
		    	<h3 class="panel-title">SIGN IN</h3>
		  	</div>
		  	<div class="panel-body">
		    	<?php $form->setAttribute('action', $this->url('backend/default', array('controller' => 'index', 'action' => 'login' )))->prepare(); ?>
                <?php echo $this->form()->openTag($form); ?>
    			<div class="row">
                    <?php //echo $this->formLabel($this->form->get('phone')); ?>
                    <div class="input-group-sm col-lg-12">
                        <?php echo $this->formInput($this->form->get('login')); ?>
                        <?php echo $this->FormElementErrors($this->form->get('login')); ?>
                    </div>
                </div>
                <div class="row">
                    <?php //echo $this->formLabel($this->form->get('phone')); ?>
                    <div class="input-group-sm col-lg-12">
                        <?php echo $this->formInput($this->form->get('password')); ?>
                        <?php echo $this->FormElementErrors($this->form->get('password')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="input-group-sm col-lg-12">
                        <?php echo $this->formSubmit($this->form->get('submit')); ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag($form); ?>
		  	</div>
		</div>
	</div>
</div>