<head>



<!--

************************************************************

Copyright Warning.

************************************************************

All content on this HTML email template is copyrighted,
No personal or commercial use is permitted without
a license.

This email template is sold exlusively on ThemeForest
by robbieWilliams.

No reproduction in whole or in part, of the content of
this email template in any form whatsoever is permitted,
whether made for commercial gain or otherwise.

************************************************************

background-image:                    background/bg09.jpg    #223552
background-color:                    #fefefe
Preheader_Color:                     #f3f3f3
Content_Color                        #ffffff

Color01:                             #a3a379    #223552
Color02:                             #CCCC99

Title & Text Color:                  #151516
Small Text Color:                    #5f5f5f

-->

<!-- Define Charset -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<!-- Responsive Meta Tag -->
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">

<!-- Facebook sharing information tags -->
<meta property="og:title" content="*|MC:SUBJECT|*">

<title>*|MC:SUBJECT|*</title>

<style type="text/css">/* iPad Text Smoother */


        .ReadMsgBody {width: 100%; background-color: #ffffff;}
        .ExternalClass {width: 100%; background-color: #ffffff;}
        body     {width: 100%; background-color: #ffffff; margin:0; padding:0; -webkit-font-smoothing: antialiased;font-family: Arial, Helvetica, sans-serif}
        table {border-collapse: collapse;}
        
        @media only screen and (max-width: 640px)  {
                        body[yahoo] .deviceWidth {width:440px!important; padding:0;}    
                        body[yahoo] .center {text-align: center!important;}  
                }
                
        @media only screen and (max-width: 479px) {
                        body[yahoo] .deviceWidth {width:280px!important; padding:0;}    
                        body[yahoo] .center {text-align: center!important;}  
                }
    

div, p, a, li, td { -webkit-text-size-adjust:none; }

.ReadMsgBody
{width: 100%; background-color: #ffffff;}
.ExternalClass
{width: 100%; background-color: #ffffff;}
body
{width: 100%; background-color: #ffffff; margin:0; padding:0; -webkit-font-smoothing: antialiased; mso-margin-top-alt:0px; mso-margin-bottom-alt:0px; mso-padding-alt: 0px 0px 0px 0px;}
html
{width: 100%; }
img 
{   border:0px; outline:none;   text-decoration:none;   display:block; }

a
{
  text-decoration: none;
  text-transform: capitalize;
  line-height: 30px;
  color: #ffffff;
}

a span
{
    text-decoration:none;
    color: #ffffff;
}
 
h1 {
  font-size: 30px;
  margin: 20px 0 20px 0;
  font-family: Myriad Pro, Helvetica, Arial, sans-serif;
  font-weight: normal;
  font-style: normal;
  color: #151516;
  text-align: left;
  line-height:40px;
 }
 
h2 {
    font-size: 18px;
    margin: 10px 0 10px 0;
    color: #808185; 
    text-align: left; 
    font-weight: normal; 
    font-family: Myriad Pro, Helvetica, Arial, sans-serif !important; 
    line-height: 22px;
    text-decoration:none;
    text-transform:uppercase;
}
  
h3 {
    font-size: 12px;
    margin: 5px 0 5px 0;
    color: #808185; 
    text-align: left; 
    font-weight: normal; 
    font-family: Helvetica, Arial, sans-serif; 
    line-height: 18px;
}

@media only screen and (max-width: 900px) 
{
    td[class=headerBG] {width: 100%!important; background-repeat: no-repeat!important; background-size: 900px!important; background-position: center middle!important;}
}
    
@media only screen and (max-width: 640px)
{  
    body{ width:auto!important; }
       
  /* Box Wrap */
  .BoxWrap { width:440px !important;  }
  
  /* Show/Hide  */
  .RespoHideMedium { display:none !important; } 
  .RespoShowMedium { display:block !important; } 
  .RespoCenterMedium { text-align:center !important; }
    

  td[class=headerBG] {width: 100%!important;  background-repeat: no-repeat!important; background-size: 800px!important; background-position: center!important;}
  
  img[class=RespoImage_OneTo50W],img[class=RespoImage_OneTo50]   { width: 440px!important; height: 212px!important; }
  img[class=RespoImage_OneTo75W],img[class=RespoImage_OneTo75] { width: 440px!important; height: 335px!important; }
  img[class=RespoImage_OneToOneW],img[class=RespoImage_OneToOne] { width: 440px!important; height: 440px!important; }
  img[class=RespoImage_70ToOneW],img[class=RespoImage_70ToOne] { width: 440px!important; height: 628px!important; }
}
        
@media only screen and (max-width: 479px)
{
  body{width:auto!important;}
  
  /* Box Wrap */
  .BoxWrap { width:280px !important;  }
        
  /* Hide  */
  .RespoHideSmall { display:none !important; }
  .RespoCenterSmall { text-align:center !important; }

  img[class=RespoImage_OneTo50W],img[class=RespoImage_OneTo50]   { width: 280px!important; height: 135px!important; }
  img[class=RespoImage_OneTo75W],img[class=RespoImage_OneTo75] { width: 280px!important; height: 213px!important; }
  img[class=RespoImage_OneToOneW],img[class=RespoImage_OneToOne] { width: 280px!important; height: 280px!important; }
  img[class=RespoImage_70ToOneW],img[class=RespoImage_70ToOne] { width: 280px!important; height: 400px!important; }

}

/**
* @tab Background
* @section Background Color
* @tip Set the background color for your email's body content blocks.
*/
.Bg_Color
{
     /*@editable*/ background-color: #687074;
}


/**
* @tab Background
* @section Image Alternative Color
* @tip Set the background image alternative color for non-supported browsers.
*/
.BgImageAltColor
{
     /*@editable*/ background-color: #223552;
}

/**
* @tab Background
* @section preheader color
* @tip Set the background color for your email's preheader block.
*/
.Preheader_Color
{
     /*@editable*/ background-color: #f3f3f3;
}

/**
* @tab Content
* @section content block01
* @tip Set the background color for your email's body content blocks.
*/
.Content_Color
{
     /*@editable*/ background-color: #ffffff;
}

/**
* @tab Colors
* @section Color01_Bright
* @tip Set the background color for your email's body content blocks.
*/
.Color01_B
{
     /*@editable*/ background-color: #a3a379;
}

/**
* @tab Colors
* @section Color01_Dark
* @tip Set the background color for your email's body content blocks.
*/
.Color01_D
{
     /*@editable*/ background-color: #223552;
}

/**
* @tab Colors
* @section Color02_Bright
* @tip Set the background color for your email's body content blocks.
*/
.Color02_B
{
     /*@editable*/ background-color: #CCCC99;
}</style>
</head>

<?php echo $this->content; ?>
